import DNDSR.DNDS._ext.dnds_pybind11
import DNDSR.DNDS._ext.dnds_pybind11.Serializer
from __future__ import annotations
import collections.abc
import numpy
import numpy.typing
import typing
from . import Elem
__all__: list[str] = ['ArrayTransformer_ElemInfo_1_1_Unknown', 'Array_ElemInfo_1_1_Unknown', 'AutoAppendName2ID', 'Elem', 'ElemInfo', 'MeshLoc', 'ParArrayPair_ElemInfo_1_1_Unknown', 'ParArray_ElemInfo_1_1_Unknown', 'UnstructuredMesh', 'UnstructuredMeshSerialRW']
class ArrayTransformer_ElemInfo_1_1_Unknown:
    LGhostMapping: DNDSR.DNDS._ext.dnds_pybind11.OffsetAscendIndexMapping
    LGlobalMapping: DNDSR.DNDS._ext.dnds_pybind11.GlobalOffsetsMapping
    father: ParArray_ElemInfo_1_1_Unknown
    mpi: DNDSR.DNDS._ext.dnds_pybind11.MPIInfo
    son: ParArray_ElemInfo_1_1_Unknown
    def BorrowGGIndexing(self, other: typing.Any) -> None:
        ...
    def __init__(self) -> None:
        ...
    def clearMPITypes(self) -> None:
        ...
    def clearPersistentPull(self) -> None:
        ...
    def clearPersistentPush(self) -> None:
        ...
    def createFatherGlobalMapping(self) -> None:
        ...
    @typing.overload
    def createGhostMapping(self, pullIndexGlobal: collections.abc.Sequence[typing.SupportsInt]) -> None:
        ...
    @typing.overload
    def createGhostMapping(self, pullIndexGlobal: typing.Annotated[numpy.typing.ArrayLike, numpy.int64]) -> None:
        ...
    @typing.overload
    def createGhostMapping(self, pushingIndexLocal: collections.abc.Sequence[typing.SupportsInt], pushingStarts: collections.abc.Sequence[typing.SupportsInt]) -> None:
        ...
    def createMPITypes(self) -> None:
        ...
    def initPersistentPull(self, backend: DNDSR.DNDS._ext.dnds_pybind11.DeviceBackend = ...) -> None:
        ...
    def initPersistentPush(self, backend: DNDSR.DNDS._ext.dnds_pybind11.DeviceBackend = ...) -> None:
        ...
    def pullOnce(self) -> None:
        ...
    def pushOnce(self) -> None:
        ...
    def setFatherSon(self, father: ParArray_ElemInfo_1_1_Unknown, son: ParArray_ElemInfo_1_1_Unknown) -> None:
        ...
    def startPersistentPull(self, backend: DNDSR.DNDS._ext.dnds_pybind11.DeviceBackend = ...) -> None:
        ...
    def startPersistentPush(self, backend: DNDSR.DNDS._ext.dnds_pybind11.DeviceBackend = ...) -> None:
        ...
    def waitPersistentPull(self, backend: DNDSR.DNDS._ext.dnds_pybind11.DeviceBackend = ...) -> None:
        ...
    def waitPersistentPush(self, backend: DNDSR.DNDS._ext.dnds_pybind11.DeviceBackend = ...) -> None:
        ...
class Array_ElemInfo_1_1_Unknown:
    @typing.overload
    def Resize(self, nRow: typing.SupportsInt) -> None:
        ...
    @typing.overload
    def Resize(self, nRow: typing.SupportsInt, rowsizeDynamic: typing.SupportsInt) -> None:
        ...
    @typing.overload
    def Rowsize(self, iRow: typing.SupportsInt) -> int:
        ...
    @typing.overload
    def Rowsize(self) -> int:
        ...
    def Size(self) -> int:
        ...
    def __getitem__(self, arg0: tuple[typing.SupportsInt, typing.SupportsInt]) -> ElemInfo:
        ...
    def __init__(self) -> None:
        ...
    def __setitem__(self, arg0: tuple[typing.SupportsInt, typing.SupportsInt], arg1: ElemInfo) -> None:
        ...
    def clone(self) -> Array_ElemInfo_1_1_Unknown:
        ...
    def data(self) -> memoryview:
        ...
    def device(self) -> DNDSR.DNDS._ext.dnds_pybind11.DeviceBackend:
        ...
    def getRowSizes(self) -> memoryview:
        ...
    def getRowStart(self) -> memoryview:
        ...
    def to_device(self, backend: str) -> None:
        ...
    def to_host(self) -> None:
        ...
class AutoAppendName2ID:
    def __call__(self, arg0: str) -> int:
        ...
    def __init__(self) -> None:
        ...
    @property
    def id_cap(self) -> int:
        ...
    @property
    def n2id_map(self) -> dict[str, int]:
        ...
class ElemInfo:
    def getElemType(self) -> Elem.ElemType:
        ...
    def setElemType(self, arg0: Elem.ElemType) -> None:
        ...
    @property
    def zone(self) -> int:
        ...
    @zone.setter
    def zone(self, arg0: typing.SupportsInt) -> None:
        ...
class MeshLoc:
    """
    Members:
    
      Unknown
    
      Node
    
      Face
    
      Cell
    """
    Cell: typing.ClassVar[MeshLoc]  # value = <MeshLoc.Cell: 4>
    Face: typing.ClassVar[MeshLoc]  # value = <MeshLoc.Face: 3>
    Node: typing.ClassVar[MeshLoc]  # value = <MeshLoc.Node: 1>
    Unknown: typing.ClassVar[MeshLoc]  # value = <MeshLoc.Unknown: 0>
    __members__: typing.ClassVar[dict[str, MeshLoc]]  # value = {'Unknown': <MeshLoc.Unknown: 0>, 'Node': <MeshLoc.Node: 1>, 'Face': <MeshLoc.Face: 3>, 'Cell': <MeshLoc.Cell: 4>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class ParArrayPair_ElemInfo_1_1_Unknown:
    father: ParArray_ElemInfo_1_1_Unknown
    son: ParArray_ElemInfo_1_1_Unknown
    @typing.overload
    def RowSize(self, i: typing.SupportsInt) -> int:
        ...
    @typing.overload
    def RowSize(self) -> int:
        ...
    def Size(self) -> int:
        ...
    def TransAttach(self) -> None:
        ...
    def __getitem__(self, arg0: tuple[typing.SupportsInt, typing.SupportsInt]) -> ElemInfo:
        ...
    def __init__(self) -> None:
        ...
    def __setitem__(self, arg0: tuple[typing.SupportsInt, typing.SupportsInt], arg1: ElemInfo) -> None:
        ...
    def clone(self) -> ParArrayPair_ElemInfo_1_1_Unknown:
        ...
    def hash(self) -> int:
        ...
    def to_device(self, backend: str) -> None:
        ...
    def to_host(self) -> None:
        ...
    @property
    def trans(self) -> ArrayTransformer_ElemInfo_1_1_Unknown:
        ...
class ParArray_ElemInfo_1_1_Unknown(Array_ElemInfo_1_1_Unknown):
    def __init__(self, n_mpi: DNDSR.DNDS._ext.dnds_pybind11.MPIInfo) -> None:
        ...
    def clone(self) -> ParArray_ElemInfo_1_1_Unknown:
        ...
    def createGlobalMapping(self) -> None:
        ...
    def getLGlobalMapping(self) -> DNDSR.DNDS._ext.dnds_pybind11.GlobalOffsetsMapping:
        ...
    def getMPI(self) -> DNDSR.DNDS._ext.dnds_pybind11.MPIInfo:
        ...
    def getTrans(self) -> type:
        ...
    def setMPI(self, n_mpi: DNDSR.DNDS._ext.dnds_pybind11.MPIInfo) -> None:
        ...
class UnstructuredMesh:
    class WallDistOptions:
        def __init__(self) -> None:
            ...
        @property
        def method(self) -> int:
            ...
        @method.setter
        def method(self, arg0: typing.SupportsInt) -> None:
            ...
        @property
        def minWallDist(self) -> float:
            ...
        @minWallDist.setter
        def minWallDist(self, arg0: typing.SupportsFloat) -> None:
            ...
        @property
        def subdivide_quad(self) -> int:
            ...
        @subdivide_quad.setter
        def subdivide_quad(self, arg0: typing.SupportsInt) -> None:
            ...
        @property
        def verbose(self) -> int:
            ...
        @verbose.setter
        def verbose(self, arg0: typing.SupportsInt) -> None:
            ...
        @property
        def wallDistExecution(self) -> int:
            ...
        @wallDistExecution.setter
        def wallDistExecution(self, arg0: typing.SupportsInt) -> None:
            ...
    def AdjGlobal2LocalC2F(self) -> None:
        ...
    def AdjGlobal2LocalFacial(self) -> None:
        ...
    def AdjGlobal2LocalN2CB(self) -> None:
        ...
    def AdjGlobal2LocalPrimary(self) -> None:
        ...
    def AdjGlobal2LocalPrimaryForBnd(self) -> None:
        ...
    def AdjLocal2GlobalC2F(self) -> None:
        ...
    def AdjLocal2GlobalFacial(self) -> None:
        ...
    def AdjLocal2GlobalN2CB(self) -> None:
        ...
    def AdjLocal2GlobalPrimary(self) -> None:
        ...
    def AdjLocal2GlobalPrimaryForBnd(self) -> None:
        ...
    def AssertOnFaces(self) -> None:
        ...
    def AssertOnN2CB(self) -> None:
        ...
    def BuildBisectO1FormO2(self, arg0: UnstructuredMesh) -> None:
        ...
    def BuildGhostN2CB(self) -> None:
        ...
    def BuildGhostPrimary(self) -> None:
        ...
    def BuildNodeWallDist(self, fBndIsWall: collections.abc.Callable[[typing.SupportsInt], bool], options: UnstructuredMesh.WallDistOptions = ...) -> None:
        ...
    def BuildO2FromO1Elevation(self, arg0: UnstructuredMesh) -> None:
        ...
    def BuildVTKConnectivity(self) -> None:
        ...
    def CellFaceOther(self, iCell: typing.SupportsInt, iFace: typing.SupportsInt) -> int:
        ...
    def CellIsFaceBack(self, iCell: typing.SupportsInt, iFace: typing.SupportsInt) -> bool:
        ...
    def ConstructBndMesh(self, bndMesh: UnstructuredMesh) -> None:
        ...
    def GetCell2CellFaceVLocal(self, arg0: bool) -> list[list[int]]:
        ...
    def InterpolateFace(self) -> None:
        ...
    def NumBnd(self) -> int:
        ...
    def NumBndGhost(self) -> int:
        ...
    def NumBndGlobal(self) -> int:
        ...
    def NumBndProc(self) -> int:
        ...
    def NumCell(self) -> int:
        ...
    def NumCellGhost(self) -> int:
        ...
    def NumCellGlobal(self) -> int:
        ...
    def NumCellProc(self) -> int:
        ...
    def NumFace(self) -> int:
        ...
    def NumFaceGhost(self) -> int:
        ...
    def NumFaceGlobal(self) -> int:
        ...
    def NumFaceProc(self) -> int:
        ...
    def NumNode(self) -> int:
        ...
    def NumNodeGhost(self) -> int:
        ...
    def NumNodeGlobal(self) -> int:
        ...
    def NumNodeProc(self) -> int:
        ...
    def ReadSerialize(self, serializer: DNDSR.DNDS._ext.dnds_pybind11.Serializer.SerializerBase, name: str) -> None:
        ...
    def RecoverCell2CellAndBnd2Cell(self) -> None:
        ...
    def RecoverNode2CellAndNode2Bnd(self) -> None:
        ...
    def RecreatePeriodicNodes(self) -> None:
        ...
    def ReorderLocalCells(self, nParts: typing.SupportsInt = 1, nPartsInner: typing.SupportsInt = 1) -> None:
        ...
    def SetPeriodicGeometry(self, translation1: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"] = ..., rotationCenter1: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"] = ..., eulerAngles1: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"] = ..., translation2: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"] = ..., rotationCenter2: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"] = ..., eulerAngles2: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"] = ..., translation3: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"] = ..., rotationCenter3: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"] = ..., eulerAngles3: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"] = ...) -> None:
        ...
    def WriteSerialize(self, serializer: DNDSR.DNDS._ext.dnds_pybind11.Serializer.SerializerBase, name: str) -> None:
        ...
    def __init__(self, arg0: DNDSR.DNDS._ext.dnds_pybind11.MPIInfo, arg1: typing.SupportsInt) -> None:
        ...
    def getArrayBytes(self) -> int:
        ...
    def getDim(self) -> int:
        ...
    def getMPI(self) -> DNDSR.DNDS._ext.dnds_pybind11.MPIInfo:
        ...
    def to_device(self, backend: str) -> None:
        ...
    def to_host(self) -> None:
        ...
    @property
    def bnd2cell(self) -> DNDSR.DNDS._ext.dnds_pybind11.ArrayAdjacencyPair_2_2_Unknown:
        ...
    @property
    def bnd2node(self) -> DNDSR.DNDS._ext.dnds_pybind11.ArrayAdjacencyPair_I_I_Unknown:
        ...
    @property
    def bndElemInfo(self) -> ParArrayPair_ElemInfo_1_1_Unknown:
        ...
    @property
    def cell2cell(self) -> DNDSR.DNDS._ext.dnds_pybind11.ArrayAdjacencyPair_I_I_Unknown:
        ...
    @property
    def cell2cellOrig(self) -> DNDSR.DNDS._ext.dnds_pybind11.ArrayAdjacencyPair_1_1_Unknown:
        ...
    @property
    def cell2face(self) -> DNDSR.DNDS._ext.dnds_pybind11.ArrayAdjacencyPair_I_I_Unknown:
        ...
    @property
    def cell2node(self) -> DNDSR.DNDS._ext.dnds_pybind11.ArrayAdjacencyPair_I_I_Unknown:
        ...
    @property
    def cellElemInfo(self) -> ParArrayPair_ElemInfo_1_1_Unknown:
        ...
    @property
    def coords(self) -> DNDSR.DNDS._ext.dnds_pybind11.ArrayEigenVectorPair_3_3_Unknown:
        ...
    @property
    def face2cell(self) -> DNDSR.DNDS._ext.dnds_pybind11.ArrayAdjacencyPair_2_2_Unknown:
        ...
    @property
    def face2node(self) -> DNDSR.DNDS._ext.dnds_pybind11.ArrayAdjacencyPair_I_I_Unknown:
        ...
    @property
    def faceElemInfo(self) -> ParArrayPair_ElemInfo_1_1_Unknown:
        ...
    @property
    def node2nodeOrig(self) -> DNDSR.DNDS._ext.dnds_pybind11.ArrayAdjacencyPair_1_1_Unknown:
        ...
class UnstructuredMeshSerialRW:
    mesh: UnstructuredMesh
    def BuildCell2Cell(self) -> None:
        ...
    def BuildSerialOut(self) -> None:
        ...
    def Deduplicate1to1Periodic(self, arg0: typing.SupportsFloat) -> None:
        ...
    def MeshPartitionCell2Cell(self, options: typing.Any = None) -> None:
        ...
    def PartitionReorderToMeshCell2Cell(self) -> None:
        ...
    def ReadFromCGNSSerial(self, arg0: str) -> AutoAppendName2ID:
        ...
    def __init__(self, mesh: UnstructuredMesh, mRank: typing.SupportsInt = 0) -> None:
        ...
    @property
    def dataIsSerialIn(self) -> bool:
        ...
    @property
    def dataIsSerialOut(self) -> bool:
        ...
