import DNDSR.DNDS._ext.dnds_pybind11
from DNDSR.DNDS._ext.dnds_pybind11 import ArrayDOF_1_1 as tUDof_1
from DNDSR.DNDS._ext.dnds_pybind11 import ArrayDOF_2_1 as tUGrad_2x1
from DNDSR.DNDS._ext.dnds_pybind11 import ArrayDOF_2_1 as tUDof_2
from DNDSR.DNDS._ext.dnds_pybind11 import ArrayDOF_2_2 as tUGrad_2x2
from DNDSR.DNDS._ext.dnds_pybind11 import ArrayDOF_2_3 as tUGrad_2x3
from DNDSR.DNDS._ext.dnds_pybind11 import ArrayDOF_2_4 as tUGrad_2x4
from DNDSR.DNDS._ext.dnds_pybind11 import ArrayDOF_2_5 as tUGrad_2x5
from DNDSR.DNDS._ext.dnds_pybind11 import ArrayDOF_2_6 as tUGrad_2x6
from DNDSR.DNDS._ext.dnds_pybind11 import ArrayDOF_2_7 as tUGrad_2x7
from DNDSR.DNDS._ext.dnds_pybind11 import ArrayDOF_2_D as tUGrad_2xD
from DNDSR.DNDS._ext.dnds_pybind11 import ArrayDOF_3_1 as tUDof_3
from DNDSR.DNDS._ext.dnds_pybind11 import ArrayDOF_3_1 as tUGrad_3x1
from DNDSR.DNDS._ext.dnds_pybind11 import ArrayDOF_3_2 as tUGrad_3x2
from DNDSR.DNDS._ext.dnds_pybind11 import ArrayDOF_3_3 as tUGrad_3x3
from DNDSR.DNDS._ext.dnds_pybind11 import ArrayDOF_3_4 as tUGrad_3x4
from DNDSR.DNDS._ext.dnds_pybind11 import ArrayDOF_3_5 as tUGrad_3x5
from DNDSR.DNDS._ext.dnds_pybind11 import ArrayDOF_3_6 as tUGrad_3x6
from DNDSR.DNDS._ext.dnds_pybind11 import ArrayDOF_3_7 as tUGrad_3x7
from DNDSR.DNDS._ext.dnds_pybind11 import ArrayDOF_3_D as tUGrad_3xD
from DNDSR.DNDS._ext.dnds_pybind11 import ArrayDOF_4_1 as tUDof_4
from DNDSR.DNDS._ext.dnds_pybind11 import ArrayDOF_5_1 as tUDof_5
from DNDSR.DNDS._ext.dnds_pybind11 import ArrayDOF_6_1 as tUDof_6
from DNDSR.DNDS._ext.dnds_pybind11 import ArrayDOF_7_1 as tUDof_7
from DNDSR.DNDS._ext.dnds_pybind11 import ArrayDOF_D_1 as tUDof_D
from DNDSR.DNDS._ext.dnds_pybind11 import ArrayDOF_D_1 as tURec_1
from DNDSR.DNDS._ext.dnds_pybind11 import ArrayDOF_D_2 as tURec_2
from DNDSR.DNDS._ext.dnds_pybind11 import ArrayDOF_D_3 as tURec_3
from DNDSR.DNDS._ext.dnds_pybind11 import ArrayDOF_D_4 as tURec_4
from DNDSR.DNDS._ext.dnds_pybind11 import ArrayDOF_D_5 as tURec_5
from DNDSR.DNDS._ext.dnds_pybind11 import ArrayDOF_D_6 as tURec_6
from DNDSR.DNDS._ext.dnds_pybind11 import ArrayDOF_D_7 as tURec_7
from DNDSR.DNDS._ext.dnds_pybind11 import ArrayDOF_D_D as tURec_D
from DNDSR.DNDS._ext.dnds_pybind11 import ArrayEigenUniMatrixBatchPair_DxD as tMatsPair
from DNDSR.DNDS._ext.dnds_pybind11 import ArrayEigenVectorPair_D_D_Unknown as tVVecPair
import DNDSR.Geom._ext.geom_pybind11
from __future__ import annotations
import collections.abc
import numpy
import numpy.typing
import typing
from . import placeholder_submodule
__all__: list[str] = ['ArrayTransformer_RecAtr_1_1_Unknown', 'Array_RecAtr_1_1_Unknown', 'FiniteVolume', 'ModelEvaluator', 'ParArrayPair_RecAtr_1_1_Unknown', 'ParArray_RecAtr_1_1_Unknown', 'RecAtr', 'VariationalReconstruction_2', 'VariationalReconstruction_3', 'finiteVolumeCellOpTest_Fixed_main_Host_N1', 'finiteVolumeCellOpTest_Fixed_main_Host_N5', 'finiteVolumeCellOpTest_SOA_ver0_main_Host_N1', 'finiteVolumeCellOpTest_SOA_ver0_main_Host_N5', 'finiteVolumeCellOpTest_main_Host', 'placeholder_submodule', 'tMatsPair', 'tRecAtrPair', 'tUDof_1', 'tUDof_2', 'tUDof_3', 'tUDof_4', 'tUDof_5', 'tUDof_6', 'tUDof_7', 'tUDof_D', 'tUGrad_2x1', 'tUGrad_2x2', 'tUGrad_2x3', 'tUGrad_2x4', 'tUGrad_2x5', 'tUGrad_2x6', 'tUGrad_2x7', 'tUGrad_2xD', 'tUGrad_3x1', 'tUGrad_3x2', 'tUGrad_3x3', 'tUGrad_3x4', 'tUGrad_3x5', 'tUGrad_3x6', 'tUGrad_3x7', 'tUGrad_3xD', 'tURec_1', 'tURec_2', 'tURec_3', 'tURec_4', 'tURec_5', 'tURec_6', 'tURec_7', 'tURec_D', 'tVVecPair']
class ArrayTransformer_RecAtr_1_1_Unknown:
    LGhostMapping: DNDSR.DNDS._ext.dnds_pybind11.OffsetAscendIndexMapping
    LGlobalMapping: DNDSR.DNDS._ext.dnds_pybind11.GlobalOffsetsMapping
    father: ParArray_RecAtr_1_1_Unknown
    mpi: DNDSR.DNDS._ext.dnds_pybind11.MPIInfo
    son: ParArray_RecAtr_1_1_Unknown
    def BorrowGGIndexing(self, other: typing.Any) -> None:
        ...
    def __init__(self) -> None:
        ...
    def clearMPITypes(self) -> None:
        ...
    def clearPersistentPull(self) -> None:
        ...
    def clearPersistentPush(self) -> None:
        ...
    def createFatherGlobalMapping(self) -> None:
        ...
    @typing.overload
    def createGhostMapping(self, pullIndexGlobal: collections.abc.Sequence[typing.SupportsInt]) -> None:
        ...
    @typing.overload
    def createGhostMapping(self, pullIndexGlobal: typing.Annotated[numpy.typing.ArrayLike, numpy.int64]) -> None:
        ...
    @typing.overload
    def createGhostMapping(self, pushingIndexLocal: collections.abc.Sequence[typing.SupportsInt], pushingStarts: collections.abc.Sequence[typing.SupportsInt]) -> None:
        ...
    def createMPITypes(self) -> None:
        ...
    def initPersistentPull(self, backend: DNDSR.DNDS._ext.dnds_pybind11.DeviceBackend = ...) -> None:
        ...
    def initPersistentPush(self, backend: DNDSR.DNDS._ext.dnds_pybind11.DeviceBackend = ...) -> None:
        ...
    def pullOnce(self) -> None:
        ...
    def pushOnce(self) -> None:
        ...
    def setFatherSon(self, father: ParArray_RecAtr_1_1_Unknown, son: ParArray_RecAtr_1_1_Unknown) -> None:
        ...
    def startPersistentPull(self, backend: DNDSR.DNDS._ext.dnds_pybind11.DeviceBackend = ...) -> None:
        ...
    def startPersistentPush(self, backend: DNDSR.DNDS._ext.dnds_pybind11.DeviceBackend = ...) -> None:
        ...
    def waitPersistentPull(self, backend: DNDSR.DNDS._ext.dnds_pybind11.DeviceBackend = ...) -> None:
        ...
    def waitPersistentPush(self, backend: DNDSR.DNDS._ext.dnds_pybind11.DeviceBackend = ...) -> None:
        ...
class Array_RecAtr_1_1_Unknown:
    @typing.overload
    def Resize(self, nRow: typing.SupportsInt) -> None:
        ...
    @typing.overload
    def Resize(self, nRow: typing.SupportsInt, rowsizeDynamic: typing.SupportsInt) -> None:
        ...
    @typing.overload
    def Rowsize(self, iRow: typing.SupportsInt) -> int:
        ...
    @typing.overload
    def Rowsize(self) -> int:
        ...
    def Size(self) -> int:
        ...
    def __getitem__(self, arg0: tuple[typing.SupportsInt, typing.SupportsInt]) -> RecAtr:
        ...
    def __init__(self) -> None:
        ...
    def __setitem__(self, arg0: tuple[typing.SupportsInt, typing.SupportsInt], arg1: RecAtr) -> None:
        ...
    def clone(self) -> Array_RecAtr_1_1_Unknown:
        ...
    def data(self) -> memoryview:
        ...
    def device(self) -> DNDSR.DNDS._ext.dnds_pybind11.DeviceBackend:
        ...
    def getRowSizes(self) -> memoryview:
        ...
    def getRowStart(self) -> memoryview:
        ...
    def to_device(self, backend: str) -> None:
        ...
    def to_host(self) -> None:
        ...
class FiniteVolume:
    def BuildUDof_1(self, u: DNDSR.DNDS._ext.dnds_pybind11.ArrayDOF_1_1, nVars: typing.SupportsInt, buildSon: bool = True, buildTrans: bool = True, varloc: DNDSR.Geom._ext.geom_pybind11.MeshLoc = ...) -> None:
        ...
    def BuildUDof_4(self, u: DNDSR.DNDS._ext.dnds_pybind11.ArrayDOF_4_1, nVars: typing.SupportsInt, buildSon: bool = True, buildTrans: bool = True, varloc: DNDSR.Geom._ext.geom_pybind11.MeshLoc = ...) -> None:
        ...
    def BuildUDof_5(self, u: DNDSR.DNDS._ext.dnds_pybind11.ArrayDOF_5_1, nVars: typing.SupportsInt, buildSon: bool = True, buildTrans: bool = True, varloc: DNDSR.Geom._ext.geom_pybind11.MeshLoc = ...) -> None:
        ...
    def BuildUDof_6(self, u: DNDSR.DNDS._ext.dnds_pybind11.ArrayDOF_6_1, nVars: typing.SupportsInt, buildSon: bool = True, buildTrans: bool = True, varloc: DNDSR.Geom._ext.geom_pybind11.MeshLoc = ...) -> None:
        ...
    def BuildUDof_7(self, u: DNDSR.DNDS._ext.dnds_pybind11.ArrayDOF_7_1, nVars: typing.SupportsInt, buildSon: bool = True, buildTrans: bool = True, varloc: DNDSR.Geom._ext.geom_pybind11.MeshLoc = ...) -> None:
        ...
    def BuildUDof_D(self, u: DNDSR.DNDS._ext.dnds_pybind11.ArrayDOF_D_1, nVars: typing.SupportsInt, buildSon: bool = True, buildTrans: bool = True, varloc: DNDSR.Geom._ext.geom_pybind11.MeshLoc = ...) -> None:
        ...
    def BuildUGrad_2x1(self, u: DNDSR.DNDS._ext.dnds_pybind11.ArrayDOF_2_1, nVars: typing.SupportsInt, buildSon: bool = True, buildTrans: bool = True, varloc: DNDSR.Geom._ext.geom_pybind11.MeshLoc = ...) -> None:
        ...
    def BuildUGrad_2x4(self, u: DNDSR.DNDS._ext.dnds_pybind11.ArrayDOF_2_4, nVars: typing.SupportsInt, buildSon: bool = True, buildTrans: bool = True, varloc: DNDSR.Geom._ext.geom_pybind11.MeshLoc = ...) -> None:
        ...
    def BuildUGrad_2x5(self, u: DNDSR.DNDS._ext.dnds_pybind11.ArrayDOF_2_5, nVars: typing.SupportsInt, buildSon: bool = True, buildTrans: bool = True, varloc: DNDSR.Geom._ext.geom_pybind11.MeshLoc = ...) -> None:
        ...
    def BuildUGrad_2x6(self, u: DNDSR.DNDS._ext.dnds_pybind11.ArrayDOF_2_6, nVars: typing.SupportsInt, buildSon: bool = True, buildTrans: bool = True, varloc: DNDSR.Geom._ext.geom_pybind11.MeshLoc = ...) -> None:
        ...
    def BuildUGrad_2x7(self, u: DNDSR.DNDS._ext.dnds_pybind11.ArrayDOF_2_7, nVars: typing.SupportsInt, buildSon: bool = True, buildTrans: bool = True, varloc: DNDSR.Geom._ext.geom_pybind11.MeshLoc = ...) -> None:
        ...
    def BuildUGrad_2xD(self, u: DNDSR.DNDS._ext.dnds_pybind11.ArrayDOF_2_D, nVars: typing.SupportsInt, buildSon: bool = True, buildTrans: bool = True, varloc: DNDSR.Geom._ext.geom_pybind11.MeshLoc = ...) -> None:
        ...
    def BuildUGrad_3x1(self, u: DNDSR.DNDS._ext.dnds_pybind11.ArrayDOF_3_1, nVars: typing.SupportsInt, buildSon: bool = True, buildTrans: bool = True, varloc: DNDSR.Geom._ext.geom_pybind11.MeshLoc = ...) -> None:
        ...
    def BuildUGrad_3x4(self, u: DNDSR.DNDS._ext.dnds_pybind11.ArrayDOF_3_4, nVars: typing.SupportsInt, buildSon: bool = True, buildTrans: bool = True, varloc: DNDSR.Geom._ext.geom_pybind11.MeshLoc = ...) -> None:
        ...
    def BuildUGrad_3x5(self, u: DNDSR.DNDS._ext.dnds_pybind11.ArrayDOF_3_5, nVars: typing.SupportsInt, buildSon: bool = True, buildTrans: bool = True, varloc: DNDSR.Geom._ext.geom_pybind11.MeshLoc = ...) -> None:
        ...
    def BuildUGrad_3x6(self, u: DNDSR.DNDS._ext.dnds_pybind11.ArrayDOF_3_6, nVars: typing.SupportsInt, buildSon: bool = True, buildTrans: bool = True, varloc: DNDSR.Geom._ext.geom_pybind11.MeshLoc = ...) -> None:
        ...
    def BuildUGrad_3x7(self, u: DNDSR.DNDS._ext.dnds_pybind11.ArrayDOF_3_7, nVars: typing.SupportsInt, buildSon: bool = True, buildTrans: bool = True, varloc: DNDSR.Geom._ext.geom_pybind11.MeshLoc = ...) -> None:
        ...
    def BuildUGrad_3xD(self, u: DNDSR.DNDS._ext.dnds_pybind11.ArrayDOF_3_D, nVars: typing.SupportsInt, buildSon: bool = True, buildTrans: bool = True, varloc: DNDSR.Geom._ext.geom_pybind11.MeshLoc = ...) -> None:
        ...
    def CellFaceOther(self, iCell: typing.SupportsInt, iFace: typing.SupportsInt) -> int:
        ...
    def CellIsFaceBack(self, iCell: typing.SupportsInt, iFace: typing.SupportsInt) -> bool:
        ...
    def ConstructCellAlignedHBox(self) -> None:
        ...
    def ConstructCellBary(self) -> None:
        ...
    def ConstructCellCent(self) -> None:
        ...
    def ConstructCellIntJacobiDet(self) -> None:
        ...
    def ConstructCellIntPPhysics(self) -> None:
        ...
    def ConstructCellMajorHBoxCoordInertia(self) -> None:
        ...
    def ConstructCellSmoothScale(self) -> None:
        ...
    def ConstructCellVolume(self) -> None:
        ...
    def ConstructFaceArea(self) -> None:
        ...
    def ConstructFaceCent(self) -> None:
        ...
    def ConstructFaceIntJacobiDet(self) -> None:
        ...
    def ConstructFaceIntPPhysics(self) -> None:
        ...
    def ConstructFaceMeanNorm(self) -> None:
        ...
    def ConstructFaceUnitNorm(self) -> None:
        ...
    def GetCellAtr(self, iCell: typing.SupportsInt) -> RecAtr:
        ...
    def GetCellBary(self, iCell: typing.SupportsInt) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
    def GetCellJacobiDet(self, iCell: typing.SupportsInt, iG: typing.SupportsInt) -> float:
        ...
    def GetCellMaxLenScale(self, iCell: typing.SupportsInt) -> float:
        ...
    def GetCellOrder(self, iCell: typing.SupportsInt) -> int:
        ...
    def GetCellQuadraturePPhys(self, iCell: typing.SupportsInt, iG: typing.SupportsInt) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
    def GetCellSmoothScaleRatio(self, iCell: typing.SupportsInt) -> float:
        ...
    def GetCellVol(self, iCell: typing.SupportsInt) -> float:
        ...
    def GetFaceArea(self, iFace: typing.SupportsInt) -> float:
        ...
    def GetFaceAtr(self, iFace: typing.SupportsInt) -> RecAtr:
        ...
    def GetFaceJacobiDet(self, iFace: typing.SupportsInt, iG: typing.SupportsInt) -> float:
        ...
    def GetFaceNorm(self, iFace: typing.SupportsInt, iG: typing.SupportsInt) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
    def GetFaceNormFromCell(self, iFace: typing.SupportsInt, iCell: typing.SupportsInt, if2c: typing.SupportsInt, iG: typing.SupportsInt) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
    def GetFaceParamArea(self, iFace: typing.SupportsInt) -> float:
        ...
    def GetFacePointFromCell(self, iFace: typing.SupportsInt, iCell: typing.SupportsInt, if2c: typing.SupportsInt, pnt: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
    def GetFaceQuadraturePPhys(self, iFace: typing.SupportsInt, iG: typing.SupportsInt) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
    def GetFaceQuadraturePPhysFromCell(self, iFace: typing.SupportsInt, iCell: typing.SupportsInt, if2c: typing.SupportsInt, iG: typing.SupportsInt) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
    def GetGlobalVol(self) -> float:
        ...
    def GetOtherCellBaryFromCell(self, iCell: typing.SupportsInt, iCellOther: typing.SupportsInt, iFace: typing.SupportsInt) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
    def GetOtherCellInertiaFromCell(self, iCell: typing.SupportsInt, iCellOther: typing.SupportsInt, iFace: typing.SupportsInt) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]:
        ...
    def GetOtherCellPointFromCell(self, iCell: typing.SupportsInt, iCellOther: typing.SupportsInt, iFace: typing.SupportsInt, pnt: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
    def GetSettings(self) -> typing.Any:
        ...
    def ParseSettings(self, settings: typing.Any) -> None:
        ...
    def SetCellAtrBasic(self) -> None:
        ...
    def SetFaceAtrBasic(self) -> None:
        ...
    def __init__(self, arg0: DNDSR.DNDS._ext.dnds_pybind11.MPIInfo, arg1: DNDSR.Geom._ext.geom_pybind11.UnstructuredMesh) -> None:
        ...
    def getArrayBytes(self) -> int:
        ...
    def to_device(self, backend: str) -> None:
        ...
    def to_host(self) -> None:
        ...
class ModelEvaluator:
    class EvaluateRHSOptions:
        direct2ndRec: bool
        direct2ndRec1stConv: bool
        def __init__(self) -> None:
            ...
    def DoReconstructionIter(self, uRec: DNDSR.DNDS._ext.dnds_pybind11.ArrayDOF_D_D, uRecNew: DNDSR.DNDS._ext.dnds_pybind11.ArrayDOF_D_D, u: DNDSR.DNDS._ext.dnds_pybind11.ArrayDOF_D_1, t: typing.SupportsFloat, putIntoNew: bool = False, recordInc: bool = False, uRecIsZero: bool = False) -> None:
        ...
    def EvaluateRHS(self, rhs: DNDSR.DNDS._ext.dnds_pybind11.ArrayDOF_D_1, u: DNDSR.DNDS._ext.dnds_pybind11.ArrayDOF_D_1, uRec: DNDSR.DNDS._ext.dnds_pybind11.ArrayDOF_D_D, t: typing.SupportsFloat, options: ModelEvaluator.EvaluateRHSOptions = ...) -> None:
        ...
    def ParseSettings(self, arg0: typing.Any) -> None:
        ...
    def __init__(self, mesh: DNDSR.Geom._ext.geom_pybind11.UnstructuredMesh, vfv: VariationalReconstruction_2, settings: typing.Any, nVars: typing.SupportsInt) -> None:
        ...
    def get_FBoundary(self, t: typing.SupportsFloat) -> collections.abc.Callable[[typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"], typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"], typing.SupportsInt, typing.SupportsInt, typing.SupportsInt, typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"], typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"], typing.SupportsInt], typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]]:
        ...
class ParArrayPair_RecAtr_1_1_Unknown:
    father: ParArray_RecAtr_1_1_Unknown
    son: ParArray_RecAtr_1_1_Unknown
    @typing.overload
    def RowSize(self, i: typing.SupportsInt) -> int:
        ...
    @typing.overload
    def RowSize(self) -> int:
        ...
    def Size(self) -> int:
        ...
    def TransAttach(self) -> None:
        ...
    def __getitem__(self, arg0: tuple[typing.SupportsInt, typing.SupportsInt]) -> RecAtr:
        ...
    def __init__(self) -> None:
        ...
    def __setitem__(self, arg0: tuple[typing.SupportsInt, typing.SupportsInt], arg1: RecAtr) -> None:
        ...
    def clone(self) -> ParArrayPair_RecAtr_1_1_Unknown:
        ...
    def hash(self) -> int:
        ...
    def to_device(self, backend: str) -> None:
        ...
    def to_host(self) -> None:
        ...
    @property
    def trans(self) -> ArrayTransformer_RecAtr_1_1_Unknown:
        ...
class ParArray_RecAtr_1_1_Unknown(Array_RecAtr_1_1_Unknown):
    def __init__(self, n_mpi: DNDSR.DNDS._ext.dnds_pybind11.MPIInfo) -> None:
        ...
    def clone(self) -> ParArray_RecAtr_1_1_Unknown:
        ...
    def createGlobalMapping(self) -> None:
        ...
    def getLGlobalMapping(self) -> DNDSR.DNDS._ext.dnds_pybind11.GlobalOffsetsMapping:
        ...
    def getMPI(self) -> DNDSR.DNDS._ext.dnds_pybind11.MPIInfo:
        ...
    def getTrans(self) -> type:
        ...
    def setMPI(self, n_mpi: DNDSR.DNDS._ext.dnds_pybind11.MPIInfo) -> None:
        ...
class RecAtr:
    def __init__(self) -> None:
        ...
    @property
    def NDIFF(self) -> int:
        ...
    @NDIFF.setter
    def NDIFF(self, arg0: typing.SupportsInt) -> None:
        ...
    @property
    def NDOF(self) -> int:
        ...
    @NDOF.setter
    def NDOF(self, arg0: typing.SupportsInt) -> None:
        ...
    @property
    def Order(self) -> int:
        ...
    @Order.setter
    def Order(self, arg0: typing.SupportsInt) -> None:
        ...
    @property
    def intOrder(self) -> int:
        ...
    @intOrder.setter
    def intOrder(self, arg0: typing.SupportsInt) -> None:
        ...
    @property
    def relax(self) -> float:
        ...
    @relax.setter
    def relax(self, arg0: typing.SupportsFloat) -> None:
        ...
class VariationalReconstruction_2(FiniteVolume):
    def BuildUGrad_1(self, u: DNDSR.DNDS._ext.dnds_pybind11.ArrayDOF_2_1, nVars: typing.SupportsInt, buildSon: bool = True, buildTrans: bool = True) -> None:
        ...
    def BuildUGrad_4(self, u: DNDSR.DNDS._ext.dnds_pybind11.ArrayDOF_2_4, nVars: typing.SupportsInt, buildSon: bool = True, buildTrans: bool = True) -> None:
        ...
    def BuildUGrad_5(self, u: DNDSR.DNDS._ext.dnds_pybind11.ArrayDOF_2_5, nVars: typing.SupportsInt, buildSon: bool = True, buildTrans: bool = True) -> None:
        ...
    def BuildUGrad_6(self, u: DNDSR.DNDS._ext.dnds_pybind11.ArrayDOF_2_6, nVars: typing.SupportsInt, buildSon: bool = True, buildTrans: bool = True) -> None:
        ...
    def BuildUGrad_7(self, u: DNDSR.DNDS._ext.dnds_pybind11.ArrayDOF_2_7, nVars: typing.SupportsInt, buildSon: bool = True, buildTrans: bool = True) -> None:
        ...
    def BuildUGrad_D(self, u: DNDSR.DNDS._ext.dnds_pybind11.ArrayDOF_2_D, nVars: typing.SupportsInt, buildSon: bool = True, buildTrans: bool = True) -> None:
        ...
    def BuildURec_1(self, u: DNDSR.DNDS._ext.dnds_pybind11.ArrayDOF_D_1, nVars: typing.SupportsInt, buildSon: bool = True, buildTrans: bool = True) -> None:
        ...
    def BuildURec_4(self, u: DNDSR.DNDS._ext.dnds_pybind11.ArrayDOF_D_4, nVars: typing.SupportsInt, buildSon: bool = True, buildTrans: bool = True) -> None:
        ...
    def BuildURec_5(self, u: DNDSR.DNDS._ext.dnds_pybind11.ArrayDOF_D_5, nVars: typing.SupportsInt, buildSon: bool = True, buildTrans: bool = True) -> None:
        ...
    def BuildURec_6(self, u: DNDSR.DNDS._ext.dnds_pybind11.ArrayDOF_D_6, nVars: typing.SupportsInt, buildSon: bool = True, buildTrans: bool = True) -> None:
        ...
    def BuildURec_7(self, u: DNDSR.DNDS._ext.dnds_pybind11.ArrayDOF_D_7, nVars: typing.SupportsInt, buildSon: bool = True, buildTrans: bool = True) -> None:
        ...
    def BuildURec_D(self, u: DNDSR.DNDS._ext.dnds_pybind11.ArrayDOF_D_D, nVars: typing.SupportsInt, buildSon: bool = True, buildTrans: bool = True) -> None:
        ...
    def ConstructBaseAndWeight(self, map_bcId_iOrder_to_bCweight: collections.abc.Callable[[typing.SupportsInt, typing.SupportsInt], float]) -> None:
        ...
    def ConstructBaseAndWeight_map(self, map_bcId_iOrder_to_bCweight: collections.abc.Mapping[tuple[typing.SupportsInt, typing.SupportsInt], typing.SupportsFloat]) -> None:
        ...
    def ConstructMetrics(self) -> None:
        ...
    def ConstructRecCoeff(self) -> None:
        ...
    def GetCellBary(self, iCell: typing.SupportsInt) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
    def GetCellVol(self, iCell: typing.SupportsInt) -> float:
        ...
    def GetFaceArea(self, iFace: typing.SupportsInt) -> float:
        ...
    def GetFaceNorm(self, iFace: typing.SupportsInt, iG: typing.SupportsInt) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
    def GetFaceNormFromCell(self, iFace: typing.SupportsInt, iCell: typing.SupportsInt, if2c: typing.SupportsInt, ig: typing.SupportsInt) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
    def ParseSettings(self, settings: typing.Any) -> None:
        ...
    def SetPeriodicTransformations2d(self, Seq123: typing.Annotated[collections.abc.Sequence[typing.SupportsInt], "FixedSize(2)"]) -> None:
        ...
    def SetPeriodicTransformations3d(self, Seq123: typing.Annotated[collections.abc.Sequence[typing.SupportsInt], "FixedSize(3)"]) -> None:
        ...
    def SetPeriodicTransformationsNoOp(self) -> None:
        ...
    def __init__(self, mpi: DNDSR.DNDS._ext.dnds_pybind11.MPIInfo, mesh: DNDSR.Geom._ext.geom_pybind11.UnstructuredMesh) -> None:
        ...
    @property
    def matrixAAInvB(self) -> DNDSR.DNDS._ext.dnds_pybind11.ArrayEigenUniMatrixBatchPair_DxD:
        ...
    @property
    def vectorAInvB(self) -> DNDSR.DNDS._ext.dnds_pybind11.ArrayEigenUniMatrixBatchPair_DxD:
        ...
class VariationalReconstruction_3(FiniteVolume):
    def BuildUGrad_1(self, u: DNDSR.DNDS._ext.dnds_pybind11.ArrayDOF_3_1, nVars: typing.SupportsInt, buildSon: bool = True, buildTrans: bool = True) -> None:
        ...
    def BuildUGrad_5(self, u: DNDSR.DNDS._ext.dnds_pybind11.ArrayDOF_3_5, nVars: typing.SupportsInt, buildSon: bool = True, buildTrans: bool = True) -> None:
        ...
    def BuildUGrad_6(self, u: DNDSR.DNDS._ext.dnds_pybind11.ArrayDOF_3_6, nVars: typing.SupportsInt, buildSon: bool = True, buildTrans: bool = True) -> None:
        ...
    def BuildUGrad_7(self, u: DNDSR.DNDS._ext.dnds_pybind11.ArrayDOF_3_7, nVars: typing.SupportsInt, buildSon: bool = True, buildTrans: bool = True) -> None:
        ...
    def BuildUGrad_D(self, u: DNDSR.DNDS._ext.dnds_pybind11.ArrayDOF_3_D, nVars: typing.SupportsInt, buildSon: bool = True, buildTrans: bool = True) -> None:
        ...
    def BuildURec_1(self, u: DNDSR.DNDS._ext.dnds_pybind11.ArrayDOF_D_1, nVars: typing.SupportsInt, buildSon: bool = True, buildTrans: bool = True) -> None:
        ...
    def BuildURec_5(self, u: DNDSR.DNDS._ext.dnds_pybind11.ArrayDOF_D_5, nVars: typing.SupportsInt, buildSon: bool = True, buildTrans: bool = True) -> None:
        ...
    def BuildURec_6(self, u: DNDSR.DNDS._ext.dnds_pybind11.ArrayDOF_D_6, nVars: typing.SupportsInt, buildSon: bool = True, buildTrans: bool = True) -> None:
        ...
    def BuildURec_7(self, u: DNDSR.DNDS._ext.dnds_pybind11.ArrayDOF_D_7, nVars: typing.SupportsInt, buildSon: bool = True, buildTrans: bool = True) -> None:
        ...
    def BuildURec_D(self, u: DNDSR.DNDS._ext.dnds_pybind11.ArrayDOF_D_D, nVars: typing.SupportsInt, buildSon: bool = True, buildTrans: bool = True) -> None:
        ...
    def ConstructBaseAndWeight(self, map_bcId_iOrder_to_bCweight: collections.abc.Callable[[typing.SupportsInt, typing.SupportsInt], float]) -> None:
        ...
    def ConstructBaseAndWeight_map(self, map_bcId_iOrder_to_bCweight: collections.abc.Mapping[tuple[typing.SupportsInt, typing.SupportsInt], typing.SupportsFloat]) -> None:
        ...
    def ConstructMetrics(self) -> None:
        ...
    def ConstructRecCoeff(self) -> None:
        ...
    def GetCellBary(self, iCell: typing.SupportsInt) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
    def GetCellVol(self, iCell: typing.SupportsInt) -> float:
        ...
    def GetFaceArea(self, iFace: typing.SupportsInt) -> float:
        ...
    def GetFaceNorm(self, iFace: typing.SupportsInt, iG: typing.SupportsInt) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
    def GetFaceNormFromCell(self, iFace: typing.SupportsInt, iCell: typing.SupportsInt, if2c: typing.SupportsInt, ig: typing.SupportsInt) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
    def ParseSettings(self, settings: typing.Any) -> None:
        ...
    def SetPeriodicTransformations2d(self, Seq123: typing.Annotated[collections.abc.Sequence[typing.SupportsInt], "FixedSize(2)"]) -> None:
        ...
    def SetPeriodicTransformations3d(self, Seq123: typing.Annotated[collections.abc.Sequence[typing.SupportsInt], "FixedSize(3)"]) -> None:
        ...
    def SetPeriodicTransformationsNoOp(self) -> None:
        ...
    def __init__(self, mpi: DNDSR.DNDS._ext.dnds_pybind11.MPIInfo, mesh: DNDSR.Geom._ext.geom_pybind11.UnstructuredMesh) -> None:
        ...
    @property
    def matrixAAInvB(self) -> DNDSR.DNDS._ext.dnds_pybind11.ArrayEigenUniMatrixBatchPair_DxD:
        ...
    @property
    def vectorAInvB(self) -> DNDSR.DNDS._ext.dnds_pybind11.ArrayEigenUniMatrixBatchPair_DxD:
        ...
def finiteVolumeCellOpTest_Fixed_main_Host_N1(fv: FiniteVolume, u: DNDSR.DNDS._ext.dnds_pybind11.ArrayDOF_1_1, u_grad: DNDSR.DNDS._ext.dnds_pybind11.ArrayDOF_3_1, nIter: typing.SupportsInt = 1, settings: typing.Any = None) -> None:
    ...
def finiteVolumeCellOpTest_Fixed_main_Host_N5(fv: FiniteVolume, u: DNDSR.DNDS._ext.dnds_pybind11.ArrayDOF_5_1, u_grad: DNDSR.DNDS._ext.dnds_pybind11.ArrayDOF_3_5, nIter: typing.SupportsInt = 1, settings: typing.Any = None) -> None:
    ...
def finiteVolumeCellOpTest_SOA_ver0_main_Host_N1(fv: FiniteVolume, u: typing.Annotated[collections.abc.Sequence[DNDSR.DNDS._ext.dnds_pybind11.ArrayDOF_1_1], "FixedSize(1)"], u_grad: typing.Annotated[collections.abc.Sequence[DNDSR.DNDS._ext.dnds_pybind11.ArrayDOF_3_1], "FixedSize(1)"], nIter: typing.SupportsInt = 1, settings: typing.Any = None) -> None:
    ...
def finiteVolumeCellOpTest_SOA_ver0_main_Host_N5(fv: FiniteVolume, u: typing.Annotated[collections.abc.Sequence[DNDSR.DNDS._ext.dnds_pybind11.ArrayDOF_1_1], "FixedSize(5)"], u_grad: typing.Annotated[collections.abc.Sequence[DNDSR.DNDS._ext.dnds_pybind11.ArrayDOF_3_1], "FixedSize(5)"], nIter: typing.SupportsInt = 1, settings: typing.Any = None) -> None:
    ...
def finiteVolumeCellOpTest_main_Host(fv: FiniteVolume, u: DNDSR.DNDS._ext.dnds_pybind11.ArrayDOF_D_1, u_grad: DNDSR.DNDS._ext.dnds_pybind11.ArrayDOF_3_D, nIter: typing.SupportsInt = 1, settings: typing.Any = None) -> None:
    ...
tRecAtrPair = ParArrayPair_RecAtr_1_1_Unknown
