#pragma once
// Auto-generated by tools/gen_shape_functions -- DO NOT EDIT
// Element: Hex8
// Regenerate: /usr/bin/python3 -m tools.gen_shape_functions.generate

#include "DNDS/Defines.hpp"
#include "Geom/Geometric.hpp"
#include "Geom/ElemEnum.hpp"

namespace DNDS::Geom::Elem
{

    // Forward declaration (primary template is in Elements.hpp)
    template <ElemType> struct ShapeFuncImpl;

    template <>
    struct ShapeFuncImpl<Hex8>
    {
        template <class TPoint, class TArray>
        DNDS_DEVICE_CALLABLE static inline void Diff0(const TPoint &p, TArray &&v)
        {
            t_real xi = p[0];
            t_real et = p[1];
            t_real zt = p[2];
            const t_real _t0 = xi - 1;
            const t_real _t1 = et - 1;
            const t_real _t2 = ((0.125))*zt + (-0.125);
            const t_real _t3 = _t1*_t2;
            const t_real _t4 = xi + 1;
            const t_real _t5 = et + 1;
            const t_real _t6 = _t2*_t5;
            const t_real _t7 = ((0.125))*zt + (0.125);
            const t_real _t8 = _t1*_t7;
            const t_real _t9 = _t5*_t7;
            v(0, 0) = -_t0*_t3;
            v(0, 1) = _t3*_t4;
            v(0, 2) = -_t4*_t6;
            v(0, 3) = _t0*_t6;
            v(0, 4) = _t0*_t8;
            v(0, 5) = -_t4*_t8;
            v(0, 6) = _t4*_t9;
            v(0, 7) = -_t0*_t9;
        }

        template <class TPoint, class TArray>
        DNDS_DEVICE_CALLABLE static inline void Diff1(const TPoint &p, TArray &&v)
        {
            t_real xi = p[0];
            t_real et = p[1];
            t_real zt = p[2];
            const t_real _t0 = et - 1;
            const t_real _t1 = ((0.125))*zt + (-0.125);
            const t_real _t2 = _t0*_t1;
            const t_real _t3 = et + 1;
            const t_real _t4 = _t1*_t3;
            const t_real _t5 = ((0.125))*zt + (0.125);
            const t_real _t6 = _t0*_t5;
            const t_real _t7 = _t3*_t5;
            const t_real _t8 = xi - 1;
            const t_real _t9 = _t1*_t8;
            const t_real _t10 = xi + 1;
            const t_real _t11 = _t1*_t10;
            const t_real _t12 = _t5*_t8;
            const t_real _t13 = _t10*_t5;
            const t_real _t14 = ((0.125))*_t0;
            const t_real _t15 = _t14*_t8;
            const t_real _t16 = _t10*_t14;
            const t_real _t17 = ((0.125))*_t3;
            const t_real _t18 = _t10*_t17;
            const t_real _t19 = _t17*_t8;
            v(0, 0) = -_t2;
            v(0, 1) = _t2;
            v(0, 2) = -_t4;
            v(0, 3) = _t4;
            v(0, 4) = _t6;
            v(0, 5) = -_t6;
            v(0, 6) = _t7;
            v(0, 7) = -_t7;
            v(1, 0) = -_t9;
            v(1, 1) = _t11;
            v(1, 2) = -_t11;
            v(1, 3) = _t9;
            v(1, 4) = _t12;
            v(1, 5) = -_t13;
            v(1, 6) = _t13;
            v(1, 7) = -_t12;
            v(2, 0) = -_t15;
            v(2, 1) = _t16;
            v(2, 2) = -_t18;
            v(2, 3) = _t19;
            v(2, 4) = _t15;
            v(2, 5) = -_t16;
            v(2, 6) = _t18;
            v(2, 7) = -_t19;
        }

        template <class TPoint, class TArray>
        DNDS_DEVICE_CALLABLE static inline void Diff2(const TPoint &p, TArray &&v)
        {
            t_real xi = p[0];
            t_real et = p[1];
            t_real zt = p[2];
            const t_real _t0 = ((0.125))*zt;
            const t_real _t1 = _t0 + (-0.125);
            const t_real _t2 = -_t1;
            const t_real _t3 = _t0 + (0.125);
            const t_real _t4 = -_t3;
            const t_real _t5 = ((0.125))*xi;
            const t_real _t6 = _t5 + (-0.125);
            const t_real _t7 = -_t6;
            const t_real _t8 = _t5 + (0.125);
            const t_real _t9 = -_t8;
            const t_real _t10 = ((0.125))*et;
            const t_real _t11 = _t10 + (-0.125);
            const t_real _t12 = -_t11;
            const t_real _t13 = _t10 + (0.125);
            const t_real _t14 = -_t13;
            v(3, 0) = _t2;
            v(3, 1) = _t1;
            v(3, 2) = _t2;
            v(3, 3) = _t1;
            v(3, 4) = _t3;
            v(3, 5) = _t4;
            v(3, 6) = _t3;
            v(3, 7) = _t4;
            v(4, 0) = _t7;
            v(4, 1) = _t8;
            v(4, 2) = _t9;
            v(4, 3) = _t6;
            v(4, 4) = _t6;
            v(4, 5) = _t9;
            v(4, 6) = _t8;
            v(4, 7) = _t7;
            v(5, 0) = _t12;
            v(5, 1) = _t11;
            v(5, 2) = _t14;
            v(5, 3) = _t13;
            v(5, 4) = _t11;
            v(5, 5) = _t12;
            v(5, 6) = _t13;
            v(5, 7) = _t14;
        }

        template <class TPoint, class TArray>
        DNDS_DEVICE_CALLABLE static inline void Diff3(const TPoint &p, TArray &&v)
        {
            t_real xi = p[0];
            t_real et = p[1];
            t_real zt = p[2];
            v(9, 0) = (-0.125);
            v(9, 1) = (0.125);
            v(9, 2) = (-0.125);
            v(9, 3) = (0.125);
            v(9, 4) = (0.125);
            v(9, 5) = (-0.125);
            v(9, 6) = (0.125);
            v(9, 7) = (-0.125);
        }
    };

} // namespace DNDS::Geom::Elem
