#pragma once
// Auto-generated by tools/gen_shape_functions -- DO NOT EDIT
// Element: Line3
// Regenerate: /usr/bin/python3 -m tools.gen_shape_functions.generate

#include "DNDS/Defines.hpp"
#include "Geom/Geometric.hpp"
#include "Geom/ElemEnum.hpp"

namespace DNDS::Geom::Elem
{

    // Forward declaration (primary template is in Elements.hpp)
    template <ElemType> struct ShapeFuncImpl;

    template <>
    struct ShapeFuncImpl<Line3>
    {
        template <class TPoint, class TArray>
        DNDS_DEVICE_CALLABLE static inline void Diff0(const TPoint &p, TArray &&v)
        {
            t_real xi = p[0];
            const t_real _t0 = ((0.5))*xi;
            v(0, 0) = _t0*(xi - 1);
            v(0, 1) = _t0*(xi + 1);
            v(0, 2) = 1 - ((xi) * (xi));
        }

        template <class TPoint, class TArray>
        DNDS_DEVICE_CALLABLE static inline void Diff1(const TPoint &p, TArray &&v)
        {
            t_real xi = p[0];
            v(0, 0) = xi + (-0.5);
            v(0, 1) = xi + (0.5);
            v(0, 2) = -2*xi;
        }

        template <class TPoint, class TArray>
        DNDS_DEVICE_CALLABLE static inline void Diff2(const TPoint &p, TArray &&v)
        {
            t_real xi = p[0];
            v(0, 0) = 1;
            v(0, 1) = 1;
            v(0, 2) = -2;
        }

        template <class TPoint, class TArray>
        DNDS_DEVICE_CALLABLE static inline void Diff3(const TPoint &p, TArray &&v)
        {
            t_real xi = p[0];
            // all zero
        }
    };

} // namespace DNDS::Geom::Elem
