#pragma once
// Auto-generated by tools/gen_shape_functions -- DO NOT EDIT
// Element: Line3
// Regenerate: /usr/bin/python3 -m tools.gen_shape_functions.generate

#include "DNDS/Defines.hpp"
#include "Geom/Geometric.hpp"
#include "Geom/ElemEnum.hpp"
#include "Geom/ElementTraitsBase.hpp"

namespace DNDS::Geom::Elem
{

    // Forward declaration (primary template is in ElementTraitsBase.hpp)
    template <ElemType> struct ShapeFuncImpl;

    // <GEN_SHAPE_FUNCS_BEGIN>
    template <>
    struct ShapeFuncImpl<Line3>
    {
        template <class TPoint, class TArray>
        DNDS_DEVICE_CALLABLE static inline void Diff0(const TPoint &p, TArray &&v)
        {
            t_real xi = p[0];
            const t_real _t0 = ((0.5))*xi;
            v(0, 0) = _t0*(xi - 1);
            v(0, 1) = _t0*(xi + 1);
            v(0, 2) = 1 - ((xi) * (xi));
        }

        template <class TPoint, class TArray>
        DNDS_DEVICE_CALLABLE static inline void Diff1(const TPoint &p, TArray &&v)
        {
            t_real xi = p[0];
            v(0, 0) = xi + (-0.5);
            v(0, 1) = xi + (0.5);
            v(0, 2) = -2*xi;
        }

        template <class TPoint, class TArray>
        DNDS_DEVICE_CALLABLE static inline void Diff2(const TPoint &p, TArray &&v)
        {
            t_real xi = p[0];
            v(0, 0) = 1;
            v(0, 1) = 1;
            v(0, 2) = -2;
        }

        template <class TPoint, class TArray>
        DNDS_DEVICE_CALLABLE static inline void Diff3(const TPoint &p, TArray &&v)
        {
            t_real xi = p[0];
            // all zero
        }
    };
    // <GEN_SHAPE_FUNCS_END>


    /**
     * @brief Element traits for 3-node quadratic line element (Line3)
     *
     * Line3 is a 1D quadratic element with nodes at the endpoints and midpoint.
     * Used as edge/face elements for 2D/3D high-order meshes.
     *
     * Geometry:
     * - Reference line: xi in [-1, 1]
     * - Node 0 at xi = -1, Node 1 at xi = +1, Node 2 at xi = 0
     */
    template <>
    struct ElementTraits<Line3>
    {
        // ============================================================
        // Core Element Identification
        // ============================================================

        /// @brief Element type enum value for static dispatch
        static constexpr ElemType elemType = Line3;

        /// @brief Spatial dimension (1 = line element)
        static constexpr int dim = 1;

        /// @brief Polynomial order of shape functions (2 = quadratic)
        static constexpr int order = 2;

        /// @brief Number of vertices (2 endpoints, same as linear)
        static constexpr int numVertices = 2;

        /// @brief Total number of nodes (3 nodes: 2 vertices + 1 midpoint)
        static constexpr int numNodes = 3;

        /// @brief Number of faces (0 for 1D element)
        static constexpr int numFaces = 0;

        /// @brief Parametric space type (line space: xi in [-1, 1])
        static constexpr ParamSpace paramSpace = LineSpace;

        /// @brief Volume of parametric space (length = 2.0)
        static constexpr t_real paramSpaceVol = 2.0;

        // ============================================================
        // Geometry Definition
        // ============================================================

        /**
         * @brief Standard coordinates of nodes in parametric space
         *
         * Format: {x, y, z} for each node. 3D coordinates for consistency.
         * Node 0: xi = -1 -> (-1, 0, 0) - left endpoint
         * Node 1: xi = +1 -> ( 1, 0, 0) - right endpoint
         * Node 2: xi =  0 -> ( 0, 0, 0) - midpoint
         */
        static constexpr std::array<t_real, 3 * 3> standardCoords = {
            -1, 0, 0,   // Node 0: left endpoint
             1, 0, 0,   // Node 1: right endpoint
             0, 0, 0};  // Node 2: midpoint

        // ============================================================
        // Face/Edge Type Queries
        // ============================================================

        /**
         * @brief Get the element type of a face
         * @param iFace Face index (unused for Line3 as it has no faces)
         * @return UnknownElem (1D elements don't have faces)
         */
        static constexpr ElemType GetFaceType(t_index /*iFace*/) { return UnknownElem; }

        // ============================================================
        // Order Elevation (P-Refinement)
        // ============================================================

        /// @brief Element type after order elevation (O2 has no higher elevation defined)
        static constexpr ElemType elevatedType = UnknownElem;

        /// @brief Number of additional nodes created during elevation (none for O2)
        static constexpr int numElevNodes = 0;

        // ============================================================
        // Bisection (Adaptive Refinement)
        // ============================================================

        /// @brief Number of sub-elements created when bisecting (2 Line2 elements)
        static constexpr int numBisect = 2;

        /// @brief Number of bisection variants (only 1 way to bisect a line)
        static constexpr int numBisectVariants = 1;

        /**
         * @brief Get the element type of a sub-element after bisection
         * @param i Sub-element index (0 or 1)
         * @return Line2 (both sub-elements are linear lines)
         */
        static constexpr ElemType GetBisectElemType(t_index /*i*/) { return Line2; }

        /**
         * @brief Node indices for each sub-element created by bisection
         *
         * Bisecting a quadratic line at the midpoint creates 2 linear lines:
         *   Sub-element 0: nodes {0, 2} - left half
         *   Sub-element 1: nodes {2, 1} - right half
         */
        static constexpr std::array<tBisectSub, 2> bisectElements = {{
            {0, 2},     // Left sub-element: nodes 0 to 2
            {2, 1}}};   // Right sub-element: nodes 2 to 1

        // ============================================================
        // VTK/Visualization Support
        // ============================================================

        /// @brief VTK cell type identifier (4 = VTK_QUADRATIC_EDGE)
        static constexpr int vtkCellType = 4;

        /**
         * @brief VTK node ordering map
         *
         * VTK uses different ordering for quadratic edge:
         *   VTK node 0 = DNDS node 0 (endpoint)
         *   VTK node 1 = DNDS node 2 (midpoint) - note the swap!
         *   VTK node 2 = DNDS node 1 (endpoint)
         */
        static constexpr std::array<int, 3> vtkNodeOrder = {0, 2, 1};
    };

} // namespace DNDS::Geom::Elem
