#pragma once
// Auto-generated by tools/gen_shape_functions -- DO NOT EDIT
// Element: Line2
// Regenerate: /usr/bin/python3 -m tools.gen_shape_functions.generate

#include "DNDS/Defines.hpp"
#include "Geom/Geometric.hpp"
#include "Geom/ElemEnum.hpp"
#include "Geom/ElementTraitsBase.hpp"

namespace DNDS::Geom::Elem
{

    // Forward declaration (primary template is in ElementTraitsBase.hpp)
    template <ElemType>
    struct ShapeFuncImpl;

    // <GEN_SHAPE_FUNCS_BEGIN>
    template <>
    struct ShapeFuncImpl<Line2>
    {
        template <class TPoint, class TArray>
        DNDS_DEVICE_CALLABLE static void Diff0(const TPoint &p, TArray &&v)
        {
            t_real xi = p[0];
            const t_real _t0 = ((0.5)) * xi;
            v(0, 0) = (0.5) - _t0;
            v(0, 1) = _t0 + (0.5);
        }

        template <class TPoint, class TArray>
        DNDS_DEVICE_CALLABLE static void Diff1(const TPoint &p, TArray &&v)
        {
            t_real xi = p[0];
            v(0, 0) = (-0.5);
            v(0, 1) = (0.5);
        }

        template <class TPoint, class TArray>
        DNDS_DEVICE_CALLABLE static void Diff2(const TPoint &p, TArray &&v)
        {
            t_real xi = p[0];
            // all zero
        }

        template <class TPoint, class TArray>
        DNDS_DEVICE_CALLABLE static void Diff3(const TPoint &p, TArray &&v)
        {
            t_real xi = p[0];
            // all zero
        }
    };
    // <GEN_SHAPE_FUNCS_END>

    // <GEN_ELEM_TRAITS_BEGIN>

    template <>
    struct ElementTraits<Line2>
    {
        static constexpr ElemType elemType = Line2;
        static constexpr int dim = 1;
        static constexpr int order = 1;
        static constexpr int numVertices = 2;
        static constexpr int numNodes = 2;
        static constexpr int numFaces = 0;
        static constexpr ParamSpace paramSpace = LineSpace;
        static constexpr t_real paramSpaceVol = 2.0;
        // 3 * NNodes is a compile-time constant; no overflow possible.
        // NOLINTNEXTLINE(bugprone-implicit-widening-of-multiplication-result)
        static constexpr std::array<t_real, 3 * 2> standardCoords = {
            -1, 0, 0, // Node 0: vertex
            1, 0, 0}; // Node 1: vertex

        static constexpr ElemType GetFaceType(t_index /*iFace*/) { return UnknownElem; }

        static constexpr ElemType elevatedType = Line3;
        static constexpr int numElevNodes = 1;

        static constexpr std::array<tElevSpan, 1> elevSpans = {{{0, 1}}};

        static constexpr std::array<ElemType, 1> elevNodeSpanTypes = {
            Line2};

        static constexpr int vtkCellType = 3;

        static constexpr std::array<int, 2> vtkNodeOrder = {0, 1};
    };
    // <GEN_ELEM_TRAITS_END>

} // namespace DNDS::Geom::Elem
