#pragma once
// Auto-generated by tools/gen_shape_functions -- DO NOT EDIT
// Element: Prism6
// Regenerate: /usr/bin/python3 -m tools.gen_shape_functions.generate

#include "DNDS/Defines.hpp"
#include "Geom/Geometric.hpp"
#include "Geom/ElemEnum.hpp"

namespace DNDS::Geom::Elem
{

    // Forward declaration (primary template is in Elements.hpp)
    template <ElemType> struct ShapeFuncImpl;

    template <>
    struct ShapeFuncImpl<Prism6>
    {
        template <class TPoint, class TArray>
        DNDS_DEVICE_CALLABLE static inline void Diff0(const TPoint &p, TArray &&v)
        {
            t_real xi = p[0];
            t_real et = p[1];
            t_real zt = p[2];
            const t_real _t0 = zt - 1;
            const t_real _t1 = ((0.5))*et + ((0.5))*xi + (-0.5);
            const t_real _t2 = -(0.5)*_t0;
            const t_real _t3 = zt + 1;
            const t_real _t4 = ((0.5))*_t3;
            v(0, 0) = _t0*_t1;
            v(0, 1) = _t2*xi;
            v(0, 2) = _t2*et;
            v(0, 3) = -_t1*_t3;
            v(0, 4) = _t4*xi;
            v(0, 5) = _t4*et;
        }

        template <class TPoint, class TArray>
        DNDS_DEVICE_CALLABLE static inline void Diff1(const TPoint &p, TArray &&v)
        {
            t_real xi = p[0];
            t_real et = p[1];
            t_real zt = p[2];
            const t_real _t0 = ((0.5))*zt;
            const t_real _t1 = _t0 + (-0.5);
            const t_real _t2 = -_t1;
            const t_real _t3 = _t0 + (0.5);
            const t_real _t4 = -_t3;
            const t_real _t5 = ((0.5))*et;
            const t_real _t6 = ((0.5))*xi;
            const t_real _t7 = _t5 + _t6 + (-0.5);
            v(0, 0) = _t1;
            v(0, 1) = _t2;
            v(0, 3) = _t4;
            v(0, 4) = _t3;
            v(1, 0) = _t1;
            v(1, 2) = _t2;
            v(1, 3) = _t4;
            v(1, 5) = _t3;
            v(2, 0) = _t7;
            v(2, 1) = -_t6;
            v(2, 2) = -_t5;
            v(2, 3) = -_t7;
            v(2, 4) = _t6;
            v(2, 5) = _t5;
        }

        template <class TPoint, class TArray>
        DNDS_DEVICE_CALLABLE static inline void Diff2(const TPoint &p, TArray &&v)
        {
            t_real xi = p[0];
            t_real et = p[1];
            t_real zt = p[2];
            v(4, 0) = (0.5);
            v(4, 2) = (-0.5);
            v(4, 3) = (-0.5);
            v(4, 5) = (0.5);
            v(5, 0) = (0.5);
            v(5, 1) = (-0.5);
            v(5, 3) = (-0.5);
            v(5, 4) = (0.5);
        }

        template <class TPoint, class TArray>
        DNDS_DEVICE_CALLABLE static inline void Diff3(const TPoint &p, TArray &&v)
        {
            t_real xi = p[0];
            t_real et = p[1];
            t_real zt = p[2];
            // all zero
        }
    };

} // namespace DNDS::Geom::Elem
