#pragma once
// Auto-generated by tools/gen_shape_functions -- DO NOT EDIT
// Element: Pyramid5
// Regenerate: /usr/bin/python3 -m tools.gen_shape_functions.generate

#include "DNDS/Defines.hpp"
#include "Geom/Geometric.hpp"
#include "Geom/ElemEnum.hpp"

namespace DNDS::Geom::Elem
{

    // Forward declaration (primary template is in Elements.hpp)
    template <ElemType> struct ShapeFuncImpl;

    template <>
    struct ShapeFuncImpl<Pyramid5>
    {
        template <class TPoint, class TArray>
        static inline void Diff0(const TPoint &p, TArray &&v)
        {
            t_real xi = p[0];
            t_real et = p[1];
            t_real zt = p[2];
            // singularity guard
            if (std::abs(1 - zt) < 1e-15)
                zt -= DNDS::signP(1 - zt) * 1e-15;
            const t_real _t0 = zt - 1;
            const t_real _t1 = _t0 + et;
            const t_real _t2 = _t0 + xi;
            const t_real _t3 = (1.0 / (4*zt - 4));
            const t_real _t4 = 1 - zt;
            const t_real _t5 = _t4 + xi;
            const t_real _t6 = ((0.25))/_t0;
            const t_real _t7 = _t4 + et;
            v(0, 0) = -_t1*_t2*_t3;
            v(0, 1) = _t1*_t5*_t6;
            v(0, 2) = -_t3*_t5*_t7;
            v(0, 3) = _t2*_t6*_t7;
            v(0, 4) = zt;
        }

        template <class TPoint, class TArray>
        static inline void Diff1(const TPoint &p, TArray &&v)
        {
            t_real xi = p[0];
            t_real et = p[1];
            t_real zt = p[2];
            // singularity guard
            if (std::abs(1 - zt) < 1e-15)
                zt -= DNDS::signP(1 - zt) * 1e-15;
            const t_real _t0 = zt - 1;
            const t_real _t1 = _t0 + et;
            const t_real _t2 = ((0.25))/_t0;
            const t_real _t3 = 1 - zt;
            const t_real _t4 = _t3 + et;
            const t_real _t5 = _t0 + xi;
            const t_real _t6 = _t3 + xi;
            const t_real _t7 = 2*zt;
            const t_real _t8 = et*xi;
            const t_real _t9 = ((zt) * (zt));
            const t_real _t10 = -_t7 + _t9 + 1;
            const t_real _t11 = ((0.25))/_t10;
            const t_real _t12 = _t11*(_t7 + _t8 - _t9 - 1);
            const t_real _t13 = _t11*(-_t10 - _t8);
            v(0, 0) = -_t1*_t2;
            v(0, 1) = _t1*_t2;
            v(0, 2) = -_t2*_t4;
            v(0, 3) = _t2*_t4;
            v(1, 0) = -_t2*_t5;
            v(1, 1) = _t2*_t6;
            v(1, 2) = -_t2*_t6;
            v(1, 3) = _t2*_t5;
            v(2, 0) = _t12;
            v(2, 1) = _t13;
            v(2, 2) = _t12;
            v(2, 3) = _t13;
            v(2, 4) = 1;
        }

        template <class TPoint, class TArray>
        static inline void Diff2(const TPoint &p, TArray &&v)
        {
            t_real xi = p[0];
            t_real et = p[1];
            t_real zt = p[2];
            // singularity guard
            if (std::abs(1 - zt) < 1e-15)
                zt -= DNDS::signP(1 - zt) * 1e-15;
            const t_real _t0 = ((zt) * (zt));
            const t_real _t1 = ((zt) * (zt) * (zt));
            const t_real _t2 = et*xi;
            const t_real _t3 = -_t2/(-6*_t0 + 2*_t1 + 6*zt - 2);
            const t_real _t4 = ((0.5))*_t2/(-3*_t0 + _t1 + 3*zt - 1);
            const t_real _t5 = -1/(4*zt - 4);
            const t_real _t6 = zt - 1;
            const t_real _t7 = ((0.25))/_t6;
            const t_real _t8 = ((0.25))/((_t6) * (_t6));
            const t_real _t9 = _t8*xi;
            const t_real _t10 = -_t9;
            const t_real _t11 = _t8*et;
            const t_real _t12 = -_t11;
            v(2, 0) = _t3;
            v(2, 1) = _t4;
            v(2, 2) = _t3;
            v(2, 3) = _t4;
            v(3, 0) = _t5;
            v(3, 1) = _t7;
            v(3, 2) = _t5;
            v(3, 3) = _t7;
            v(4, 0) = _t9;
            v(4, 1) = _t10;
            v(4, 2) = _t9;
            v(4, 3) = _t10;
            v(5, 0) = _t11;
            v(5, 1) = _t12;
            v(5, 2) = _t11;
            v(5, 3) = _t12;
        }

        template <class TPoint, class TArray>
        static inline void Diff3(const TPoint &p, TArray &&v)
        {
            t_real xi = p[0];
            t_real et = p[1];
            t_real zt = p[2];
            // singularity guard
            if (std::abs(1 - zt) < 1e-15)
                zt -= DNDS::signP(1 - zt) * 1e-15;
            const t_real _t0 = ((zt) * (zt) * (zt) * (zt));
            const t_real _t1 = ((zt) * (zt));
            const t_real _t2 = ((zt) * (zt) * (zt));
            const t_real _t3 = et*xi;
            const t_real _t4 = ((1.5))*_t3/(_t0 + 6*_t1 - 4*_t2 - 4*zt + 1);
            const t_real _t5 = -3*_t3/(2*_t0 + 12*_t1 - 8*_t2 - 8*zt + 2);
            const t_real _t6 = zt - 1;
            const t_real _t7 = ((0.5))/((_t6) * (_t6) * (_t6));
            const t_real _t8 = _t7*xi;
            const t_real _t9 = -_t8;
            const t_real _t10 = _t7*et;
            const t_real _t11 = -_t10;
            const t_real _t12 = ((0.25))/((_t6) * (_t6));
            const t_real _t13 = -_t12;
            v(2, 0) = _t4;
            v(2, 1) = _t5;
            v(2, 2) = _t4;
            v(2, 3) = _t5;
            v(6, 0) = _t9;
            v(6, 1) = _t8;
            v(6, 2) = _t9;
            v(6, 3) = _t8;
            v(7, 0) = _t11;
            v(7, 1) = _t10;
            v(7, 2) = _t11;
            v(7, 3) = _t10;
            v(9, 0) = _t12;
            v(9, 1) = _t13;
            v(9, 2) = _t12;
            v(9, 3) = _t13;
        }
    };

} // namespace DNDS::Geom::Elem
