#pragma once
// Auto-generated by tools/gen_shape_functions -- DO NOT EDIT
// Element: Quad4
// Regenerate: /usr/bin/python3 -m tools.gen_shape_functions.generate

#include "DNDS/Defines.hpp"
#include "Geom/Geometric.hpp"
#include "Geom/ElemEnum.hpp"
#include "Geom/ElementTraitsBase.hpp"

namespace DNDS::Geom::Elem
{

    // Forward declaration (primary template is in ElementTraitsBase.hpp)
    template <ElemType> struct ShapeFuncImpl;

    // <GEN_SHAPE_FUNCS_BEGIN>
    template <>
    struct ShapeFuncImpl<Quad4>
    {
        template <class TPoint, class TArray>
        DNDS_DEVICE_CALLABLE static inline void Diff0(const TPoint &p, TArray &&v)
        {
            t_real xi = p[0];
            t_real et = p[1];
            const t_real _t0 = xi - 1;
            const t_real _t1 = ((0.25))*et + (-0.25);
            const t_real _t2 = xi + 1;
            const t_real _t3 = ((0.25))*et + (0.25);
            v(0, 0) = _t0*_t1;
            v(0, 1) = -_t1*_t2;
            v(0, 2) = _t2*_t3;
            v(0, 3) = -_t0*_t3;
        }

        template <class TPoint, class TArray>
        DNDS_DEVICE_CALLABLE static inline void Diff1(const TPoint &p, TArray &&v)
        {
            t_real xi = p[0];
            t_real et = p[1];
            const t_real _t0 = ((0.25))*et;
            const t_real _t1 = _t0 + (-0.25);
            const t_real _t2 = _t0 + (0.25);
            const t_real _t3 = ((0.25))*xi;
            const t_real _t4 = _t3 + (-0.25);
            const t_real _t5 = _t3 + (0.25);
            v(0, 0) = _t1;
            v(0, 1) = -_t1;
            v(0, 2) = _t2;
            v(0, 3) = -_t2;
            v(1, 0) = _t4;
            v(1, 1) = -_t5;
            v(1, 2) = _t5;
            v(1, 3) = -_t4;
        }

        template <class TPoint, class TArray>
        DNDS_DEVICE_CALLABLE static inline void Diff2(const TPoint &p, TArray &&v)
        {
            t_real xi = p[0];
            t_real et = p[1];
            v(1, 0) = (0.25);
            v(1, 1) = (-0.25);
            v(1, 2) = (0.25);
            v(1, 3) = (-0.25);
        }

        template <class TPoint, class TArray>
        DNDS_DEVICE_CALLABLE static inline void Diff3(const TPoint &p, TArray &&v)
        {
            t_real xi = p[0];
            t_real et = p[1];
            // all zero
        }
    };
    // <GEN_SHAPE_FUNCS_END>


    /**
     * @brief Element traits for 4-node bilinear quadrilateral (Quad4)
     *
     * Quad4 is the simplest 2D quadrilateral element, commonly used for:
     * - Structured and unstructured quadrilateral meshes
     * - Boundary-fitted grids
     * - Isoparametric mapping
     *
     * Geometry:
     * - Reference quad: xi in [-1, 1], eta in [-1, 1]
     * - Nodes at the 4 corners of the reference square
     * - Parametric space area = 4.0
     *
     * Faces:
     * - 4 edges, each is a Line2 element
     */
    template <>
    struct ElementTraits<Quad4>
    {
        // ============================================================
        // Core Element Identification
        // ============================================================

        static constexpr ElemType elemType = Quad4;
        static constexpr int dim = 2;
        static constexpr int order = 1;
        static constexpr int numVertices = 4;
        static constexpr int numNodes = 4;
        static constexpr int numFaces = 4;
        static constexpr ParamSpace paramSpace = QuadSpace;
        static constexpr t_real paramSpaceVol = 4.0;

        // ============================================================
        // Geometry Definition
        // ============================================================

        /**
         * @brief Standard coordinates of nodes in parametric space
         *
         * Reference square [-1,1] x [-1,1] with nodes at corners:
         * Node 0: (-1, -1) - bottom-left
         * Node 1: ( 1, -1) - bottom-right
         * Node 2: ( 1,  1) - top-right
         * Node 3: (-1,  1) - top-left
         */
        static constexpr std::array<t_real, 3 * 4> standardCoords = {
            -1, -1, 0,   // Node 0: bottom-left
             1, -1, 0,   // Node 1: bottom-right
             1,  1, 0,   // Node 2: top-right
            -1,  1, 0};  // Node 3: top-left

        // ============================================================
        // Face/Edge Definitions
        // ============================================================

        /**
         * @brief Get the element type of a face (edge)
         * @return Line2 (all edges of quad are linear lines)
         */
        static constexpr ElemType GetFaceType(t_index /*iFace*/) { return Line2; }

        /**
         * @brief Node indices for each face (edge)
         *
         * Edge 0: nodes 0-1 (bottom edge)
         * Edge 1: nodes 1-2 (right edge)
         * Edge 2: nodes 2-3 (top edge)
         * Edge 3: nodes 3-0 (left edge)
         */
        static constexpr std::array<std::array<t_index, 10>, 4> faceNodes = {{
            {0, 1},     // Edge 0: bottom
            {1, 2},     // Edge 1: right
            {2, 3},     // Edge 2: top
            {3, 0}}};   // Edge 3: left

        // ============================================================
        // Order Elevation (P-Refinement)
        // ============================================================

        /**
         * @brief Element type after order elevation (O1 -> O2)
         * Quad4 elevates to Quad9 (9-node biquadratic quad)
         */
        static constexpr ElemType elevatedType = Quad9;

        /// @brief Number of additional nodes created during elevation
        static constexpr int numElevNodes = 5;

        /**
         * @brief Elevation spans define new node connections
         *
         * Elevation creates 5 new nodes:
         *   Spans 0-3: edge midpoints (4 nodes on edges)
         *   Span 4: body center (1 node connecting all 4 vertices)
         */
        static constexpr std::array<tElevSpan, 5> elevSpans = {{
            {0, 1},             // Edge 0 midpoint
            {1, 2},             // Edge 1 midpoint
            {2, 3},             // Edge 2 midpoint
            {3, 0},             // Edge 3 midpoint
            {0, 1, 2, 3}}};     // Body center (all 4 vertices)

        /// @brief Element type of each elevation span
        static constexpr std::array<ElemType, 5> elevNodeSpanTypes = {
            Line2, Line2, Line2, Line2,   // Edge midpoints
            Quad4};                       // Body center

        // ============================================================
        // VTK/Visualization Support
        // ============================================================

        /// @brief VTK cell type identifier (9 = VTK_QUAD)
        static constexpr int vtkCellType = 9;

        /**
         * @brief VTK node ordering map
         *
         * VTK uses the same ordering as DNDS for Quad4:
         *   VTK node 0 = DNDS node 0, VTK node 1 = DNDS node 1, etc.
         */
        static constexpr std::array<int, 4> vtkNodeOrder = {0, 1, 2, 3};
    };

} // namespace DNDS::Geom::Elem
