#pragma once
// Auto-generated by tools/gen_shape_functions -- DO NOT EDIT
// Element: Quad4
// Regenerate: /usr/bin/python3 -m tools.gen_shape_functions.generate

#include "DNDS/Defines.hpp"
#include "Geom/Geometric.hpp"
#include "Geom/ElemEnum.hpp"

namespace DNDS::Geom::Elem
{

    // Forward declaration (primary template is in Elements.hpp)
    template <ElemType> struct ShapeFuncImpl;

    template <>
    struct ShapeFuncImpl<Quad4>
    {
        template <class TPoint, class TArray>
        DNDS_DEVICE_CALLABLE static inline void Diff0(const TPoint &p, TArray &&v)
        {
            t_real xi = p[0];
            t_real et = p[1];
            const t_real _t0 = xi - 1;
            const t_real _t1 = ((0.25))*et + (-0.25);
            const t_real _t2 = xi + 1;
            const t_real _t3 = ((0.25))*et + (0.25);
            v(0, 0) = _t0*_t1;
            v(0, 1) = -_t1*_t2;
            v(0, 2) = _t2*_t3;
            v(0, 3) = -_t0*_t3;
        }

        template <class TPoint, class TArray>
        DNDS_DEVICE_CALLABLE static inline void Diff1(const TPoint &p, TArray &&v)
        {
            t_real xi = p[0];
            t_real et = p[1];
            const t_real _t0 = ((0.25))*et;
            const t_real _t1 = _t0 + (-0.25);
            const t_real _t2 = _t0 + (0.25);
            const t_real _t3 = ((0.25))*xi;
            const t_real _t4 = _t3 + (-0.25);
            const t_real _t5 = _t3 + (0.25);
            v(0, 0) = _t1;
            v(0, 1) = -_t1;
            v(0, 2) = _t2;
            v(0, 3) = -_t2;
            v(1, 0) = _t4;
            v(1, 1) = -_t5;
            v(1, 2) = _t5;
            v(1, 3) = -_t4;
        }

        template <class TPoint, class TArray>
        DNDS_DEVICE_CALLABLE static inline void Diff2(const TPoint &p, TArray &&v)
        {
            t_real xi = p[0];
            t_real et = p[1];
            v(1, 0) = (0.25);
            v(1, 1) = (-0.25);
            v(1, 2) = (0.25);
            v(1, 3) = (-0.25);
        }

        template <class TPoint, class TArray>
        DNDS_DEVICE_CALLABLE static inline void Diff3(const TPoint &p, TArray &&v)
        {
            t_real xi = p[0];
            t_real et = p[1];
            // all zero
        }
    };

} // namespace DNDS::Geom::Elem
