#pragma once
// Auto-generated by tools/gen_shape_functions -- DO NOT EDIT
// Element: Tet10
// Regenerate: /usr/bin/python3 -m tools.gen_shape_functions.generate

#include "DNDS/Defines.hpp"
#include "Geom/Geometric.hpp"
#include "Geom/ElemEnum.hpp"

namespace DNDS::Geom::Elem
{

    // Forward declaration (primary template is in Elements.hpp)
    template <ElemType> struct ShapeFuncImpl;

    template <>
    struct ShapeFuncImpl<Tet10>
    {
        template <class TPoint, class TArray>
        DNDS_DEVICE_CALLABLE static inline void Diff0(const TPoint &p, TArray &&v)
        {
            t_real xi = p[0];
            t_real et = p[1];
            t_real zt = p[2];
            const t_real _t0 = et + xi + zt - 1;
            const t_real _t1 = 2*et;
            const t_real _t2 = 2*zt;
            const t_real _t3 = 2*xi - 1;
            const t_real _t4 = -_t0;
            const t_real _t5 = 4*xi;
            const t_real _t6 = 4*_t4;
            v(0, 0) = _t0*(_t1 + _t2 + _t3);
            v(0, 1) = _t3*xi;
            v(0, 2) = et*(_t1 - 1);
            v(0, 3) = zt*(_t2 - 1);
            v(0, 4) = _t4*_t5;
            v(0, 5) = _t5*et;
            v(0, 6) = _t6*et;
            v(0, 7) = _t6*zt;
            v(0, 8) = _t5*zt;
            v(0, 9) = 4*et*zt;
        }

        template <class TPoint, class TArray>
        DNDS_DEVICE_CALLABLE static inline void Diff1(const TPoint &p, TArray &&v)
        {
            t_real xi = p[0];
            t_real et = p[1];
            t_real zt = p[2];
            const t_real _t0 = 4*xi;
            const t_real _t1 = 4*et;
            const t_real _t2 = 4*zt;
            const t_real _t3 = _t1 + _t2;
            const t_real _t4 = _t0 + _t3 - 3;
            const t_real _t5 = -_t1;
            const t_real _t6 = -_t2;
            const t_real _t7 = -_t0;
            const t_real _t8 = _t0 - 4;
            v(0, 0) = _t4;
            v(0, 1) = _t0 - 1;
            v(0, 4) = -_t3 - 8*xi + 4;
            v(0, 5) = _t1;
            v(0, 6) = _t5;
            v(0, 7) = _t6;
            v(0, 8) = _t2;
            v(1, 0) = _t4;
            v(1, 2) = _t1 - 1;
            v(1, 4) = _t7;
            v(1, 5) = _t0;
            v(1, 6) = -_t2 - _t8 - 8*et;
            v(1, 7) = _t6;
            v(1, 9) = _t2;
            v(2, 0) = _t4;
            v(2, 3) = _t2 - 1;
            v(2, 4) = _t7;
            v(2, 6) = _t5;
            v(2, 7) = -_t1 - _t8 - 8*zt;
            v(2, 8) = _t0;
            v(2, 9) = _t1;
        }

        template <class TPoint, class TArray>
        DNDS_DEVICE_CALLABLE static inline void Diff2(const TPoint &p, TArray &&v)
        {
            t_real xi = p[0];
            t_real et = p[1];
            t_real zt = p[2];
            v(0, 0) = 4;
            v(0, 1) = 4;
            v(0, 4) = -8;
            v(1, 0) = 4;
            v(1, 2) = 4;
            v(1, 6) = -8;
            v(2, 0) = 4;
            v(2, 3) = 4;
            v(2, 7) = -8;
            v(3, 0) = 4;
            v(3, 4) = -4;
            v(3, 5) = 4;
            v(3, 6) = -4;
            v(4, 0) = 4;
            v(4, 6) = -4;
            v(4, 7) = -4;
            v(4, 9) = 4;
            v(5, 0) = 4;
            v(5, 4) = -4;
            v(5, 7) = -4;
            v(5, 8) = 4;
        }

        template <class TPoint, class TArray>
        DNDS_DEVICE_CALLABLE static inline void Diff3(const TPoint &p, TArray &&v)
        {
            t_real xi = p[0];
            t_real et = p[1];
            t_real zt = p[2];
            // all zero
        }
    };

} // namespace DNDS::Geom::Elem
