#pragma once
// Auto-generated by tools/gen_shape_functions -- DO NOT EDIT
// Element: Tet4
// Regenerate: /usr/bin/python3 -m tools.gen_shape_functions.generate

#include "DNDS/Defines.hpp"
#include "Geom/Geometric.hpp"
#include "Geom/ElemEnum.hpp"
#include "Geom/ElementTraitsBase.hpp"

namespace DNDS::Geom::Elem
{

    // Forward declaration (primary template is in ElementTraitsBase.hpp)
    template <ElemType>
    struct ShapeFuncImpl;

    // <GEN_SHAPE_FUNCS_BEGIN>
    template <>
    struct ShapeFuncImpl<Tet4>
    {
        template <class TPoint, class TArray>
        DNDS_DEVICE_CALLABLE static void Diff0(const TPoint &p, TArray &&v)
        {
            t_real xi = p[0];
            t_real et = p[1];
            t_real zt = p[2];
            v(0, 0) = -et - xi - zt + 1;
            v(0, 1) = xi;
            v(0, 2) = et;
            v(0, 3) = zt;
        }

        template <class TPoint, class TArray>
        DNDS_DEVICE_CALLABLE static void Diff1(const TPoint &p, TArray &&v)
        {
            t_real xi = p[0];
            t_real et = p[1];
            t_real zt = p[2];
            v(0, 0) = -1;
            v(0, 1) = 1;
            v(1, 0) = -1;
            v(1, 2) = 1;
            v(2, 0) = -1;
            v(2, 3) = 1;
        }

        template <class TPoint, class TArray>
        DNDS_DEVICE_CALLABLE static void Diff2(const TPoint &p, TArray &&v)
        {
            t_real xi = p[0];
            t_real et = p[1];
            t_real zt = p[2];
            // all zero
        }

        template <class TPoint, class TArray>
        DNDS_DEVICE_CALLABLE static void Diff3(const TPoint &p, TArray &&v)
        {
            t_real xi = p[0];
            t_real et = p[1];
            t_real zt = p[2];
            // all zero
        }
    };
    // <GEN_SHAPE_FUNCS_END>

    // <GEN_ELEM_TRAITS_BEGIN>

    template <>
    struct ElementTraits<Tet4>
    {
        static constexpr ElemType elemType = Tet4;
        static constexpr int dim = 3;
        static constexpr int order = 1;
        static constexpr int numVertices = 4;
        static constexpr int numNodes = 4;
        static constexpr int numFaces = 4;
        static constexpr int numEdges = 6;
        static constexpr ParamSpace paramSpace = TetSpace;
        static constexpr t_real paramSpaceVol = 1.0 / 6.0;
        // 3 * NNodes is a compile-time constant; no overflow possible.
        // NOLINTNEXTLINE(bugprone-implicit-widening-of-multiplication-result)
        static constexpr std::array<t_real, 3 * 4> standardCoords = {
            0, 0, 0,  // Node 0: vertex
            1, 0, 0,  // Node 1: vertex
            0, 1, 0,  // Node 2: vertex
            0, 0, 1}; // Node 3: vertex

        static constexpr ElemType GetFaceType(t_index /*iFace*/) { return Tri3; }

        static constexpr std::array<std::array<t_index, 10>, 4> faceNodes = {{{0, 2, 1},
                                                                              {0, 1, 3},
                                                                              {1, 2, 3},
                                                                              {2, 0, 3}}};

        static constexpr ElemType GetEdgeType(t_index /*iEdge*/) { return Line2; }

        static constexpr std::array<std::array<t_index, 3>, 6> edgeNodes = {{{0, 1},
                                                                             {1, 2},
                                                                             {2, 0},
                                                                             {0, 3},
                                                                             {1, 3},
                                                                             {2, 3}}};

        static constexpr ElemType elevatedType = Tet10;
        static constexpr int numElevNodes = 6;

        static constexpr std::array<tElevSpan, 6> elevSpans = {{{0, 1},
                                                                {1, 2},
                                                                {2, 0},
                                                                {0, 3},
                                                                {1, 3},
                                                                {2, 3}}};

        static constexpr std::array<ElemType, 6> elevNodeSpanTypes = {
            Line2, Line2, Line2, Line2, Line2, Line2};

        static constexpr int vtkCellType = 10;

        static constexpr std::array<int, 4> vtkNodeOrder = {0, 1, 2, 3};
    };
    // <GEN_ELEM_TRAITS_END>

} // namespace DNDS::Geom::Elem
