#pragma once
// Auto-generated by tools/gen_shape_functions -- DO NOT EDIT
// Element: Tri3
// Regenerate: /usr/bin/python3 -m tools.gen_shape_functions.generate

#include "DNDS/Defines.hpp"
#include "Geom/Geometric.hpp"
#include "Geom/ElemEnum.hpp"
#include "Geom/ElementTraitsBase.hpp"

namespace DNDS::Geom::Elem
{

    // Forward declaration (primary template is in ElementTraitsBase.hpp)
    template <ElemType>
    struct ShapeFuncImpl;

    // <GEN_SHAPE_FUNCS_BEGIN>
    template <>
    struct ShapeFuncImpl<Tri3>
    {
        template <class TPoint, class TArray>
        DNDS_DEVICE_CALLABLE static void Diff0(const TPoint &p, TArray &&v)
        {
            t_real xi = p[0];
            t_real et = p[1];
            v(0, 0) = -et - xi + 1;
            v(0, 1) = xi;
            v(0, 2) = et;
        }

        template <class TPoint, class TArray>
        DNDS_DEVICE_CALLABLE static void Diff1(const TPoint &p, TArray &&v)
        {
            t_real xi = p[0];
            t_real et = p[1];
            v(0, 0) = -1;
            v(0, 1) = 1;
            v(1, 0) = -1;
            v(1, 2) = 1;
        }

        template <class TPoint, class TArray>
        DNDS_DEVICE_CALLABLE static void Diff2(const TPoint &p, TArray &&v)
        {
            t_real xi = p[0];
            t_real et = p[1];
            // all zero
        }

        template <class TPoint, class TArray>
        DNDS_DEVICE_CALLABLE static void Diff3(const TPoint &p, TArray &&v)
        {
            t_real xi = p[0];
            t_real et = p[1];
            // all zero
        }
    };
    // <GEN_SHAPE_FUNCS_END>

    // <GEN_ELEM_TRAITS_BEGIN>

    template <>
    struct ElementTraits<Tri3>
    {
        static constexpr ElemType elemType = Tri3;
        static constexpr int dim = 2;
        static constexpr int order = 1;
        static constexpr int numVertices = 3;
        static constexpr int numNodes = 3;
        static constexpr int numFaces = 3;
        static constexpr ParamSpace paramSpace = TriSpace;
        static constexpr t_real paramSpaceVol = 0.5;
        // 3 * NNodes is a compile-time constant; no overflow possible.
        // NOLINTNEXTLINE(bugprone-implicit-widening-of-multiplication-result)
        static constexpr std::array<t_real, 3 * 3> standardCoords = {
            0, 0, 0,  // Node 0: vertex
            1, 0, 0,  // Node 1: vertex
            0, 1, 0}; // Node 2: vertex

        static constexpr ElemType GetFaceType(t_index /*iFace*/) { return Line2; }

        static constexpr std::array<std::array<t_index, 10>, 3> faceNodes = {{{0, 1},
                                                                              {1, 2},
                                                                              {2, 0}}};

        static constexpr ElemType elevatedType = Tri6;
        static constexpr int numElevNodes = 3;

        static constexpr std::array<tElevSpan, 3> elevSpans = {{{0, 1},
                                                                {1, 2},
                                                                {2, 0}}};

        static constexpr std::array<ElemType, 3> elevNodeSpanTypes = {
            Line2, Line2, Line2};

        static constexpr int vtkCellType = 5;

        static constexpr std::array<int, 3> vtkNodeOrder = {0, 1, 2};
    };
    // <GEN_ELEM_TRAITS_END>

} // namespace DNDS::Geom::Elem
