#pragma once
// Auto-generated by tools/gen_shape_functions -- DO NOT EDIT
// Element: Tri3
// Regenerate: /usr/bin/python3 -m tools.gen_shape_functions.generate

#include "DNDS/Defines.hpp"
#include "Geom/Geometric.hpp"
#include "Geom/ElemEnum.hpp"

namespace DNDS::Geom::Elem
{

    // Forward declaration (primary template is in Elements.hpp)
    template <ElemType> struct ShapeFuncImpl;

    template <>
    struct ShapeFuncImpl<Tri3>
    {
        template <class TPoint, class TArray>
        DNDS_DEVICE_CALLABLE static inline void Diff0(const TPoint &p, TArray &&v)
        {
            t_real xi = p[0];
            t_real et = p[1];
            v(0, 0) = -et - xi + 1;
            v(0, 1) = xi;
            v(0, 2) = et;
        }

        template <class TPoint, class TArray>
        DNDS_DEVICE_CALLABLE static inline void Diff1(const TPoint &p, TArray &&v)
        {
            t_real xi = p[0];
            t_real et = p[1];
            v(0, 0) = -1;
            v(0, 1) = 1;
            v(1, 0) = -1;
            v(1, 2) = 1;
        }

        template <class TPoint, class TArray>
        DNDS_DEVICE_CALLABLE static inline void Diff2(const TPoint &p, TArray &&v)
        {
            t_real xi = p[0];
            t_real et = p[1];
            // all zero
        }

        template <class TPoint, class TArray>
        DNDS_DEVICE_CALLABLE static inline void Diff3(const TPoint &p, TArray &&v)
        {
            t_real xi = p[0];
            t_real et = p[1];
            // all zero
        }
    };

} // namespace DNDS::Geom::Elem
