#pragma once
// Auto-generated by tools/gen_shape_functions -- DO NOT EDIT
// Element: Tri6
// Regenerate: /usr/bin/python3 -m tools.gen_shape_functions.generate

#include "DNDS/Defines.hpp"
#include "Geom/Geometric.hpp"
#include "Geom/ElemEnum.hpp"

namespace DNDS::Geom::Elem
{

    // Forward declaration (primary template is in Elements.hpp)
    template <ElemType> struct ShapeFuncImpl;

    template <>
    struct ShapeFuncImpl<Tri6>
    {
        template <class TPoint, class TArray>
        DNDS_DEVICE_CALLABLE static inline void Diff0(const TPoint &p, TArray &&v)
        {
            t_real xi = p[0];
            t_real et = p[1];
            const t_real _t0 = et + xi - 1;
            const t_real _t1 = 2*et;
            const t_real _t2 = 2*xi - 1;
            const t_real _t3 = -_t0;
            const t_real _t4 = 4*xi;
            v(0, 0) = _t0*(_t1 + _t2);
            v(0, 1) = _t2*xi;
            v(0, 2) = et*(_t1 - 1);
            v(0, 3) = _t3*_t4;
            v(0, 4) = _t4*et;
            v(0, 5) = 4*_t3*et;
        }

        template <class TPoint, class TArray>
        DNDS_DEVICE_CALLABLE static inline void Diff1(const TPoint &p, TArray &&v)
        {
            t_real xi = p[0];
            t_real et = p[1];
            const t_real _t0 = 4*et;
            const t_real _t1 = 4*xi;
            const t_real _t2 = _t0 + _t1 - 3;
            v(0, 0) = _t2;
            v(0, 1) = _t1 - 1;
            v(0, 3) = -_t0 - 8*xi + 4;
            v(0, 4) = _t0;
            v(0, 5) = -_t0;
            v(1, 0) = _t2;
            v(1, 2) = _t0 - 1;
            v(1, 3) = -_t1;
            v(1, 4) = _t1;
            v(1, 5) = -_t1 - 8*et + 4;
        }

        template <class TPoint, class TArray>
        DNDS_DEVICE_CALLABLE static inline void Diff2(const TPoint &p, TArray &&v)
        {
            t_real xi = p[0];
            t_real et = p[1];
            v(0, 0) = 4;
            v(0, 1) = 4;
            v(0, 3) = -8;
            v(1, 0) = 4;
            v(1, 3) = -4;
            v(1, 4) = 4;
            v(1, 5) = -4;
            v(2, 0) = 4;
            v(2, 2) = 4;
            v(2, 5) = -8;
        }

        template <class TPoint, class TArray>
        DNDS_DEVICE_CALLABLE static inline void Diff3(const TPoint &p, TArray &&v)
        {
            t_real xi = p[0];
            t_real et = p[1];
            // all zero
        }
    };

} // namespace DNDS::Geom::Elem
