import DNDSR.DNDS._ext.dnds_pybind11
from __future__ import annotations
import typing
__all__: list[str] = ['SerializerBase', 'SerializerFactory', 'SerializerH5', 'SerializerJSON']
class SerializerBase:
    def CloseFile(self) -> None:
        ...
    def CreatePath(self, p: str) -> None:
        ...
    def GetCurrentPath(self) -> str:
        ...
    def GoToPath(self, p: str) -> None:
        ...
    def IsPerRank(self) -> bool:
        ...
    def ListCurrentPath(self) -> set[str]:
        ...
    def OpenFile(self, fName: str, read: bool) -> None:
        ...
class SerializerFactory:
    def BuildSerializer(self, mpi: DNDSR.DNDS._ext.dnds_pybind11.MPIInfo) -> SerializerBase:
        ...
    def ModifyFilePath(self, fname: str, mpi: DNDSR.DNDS._ext.dnds_pybind11.MPIInfo, rank_part_fmt: str = '%06d', read: bool = False) -> tuple[str, str]:
        ...
    def __init__(self) -> None:
        ...
    def from_dict(self, arg0: typing.Any) -> None:
        ...
    def to_dict(self) -> typing.Any:
        ...
class SerializerH5(SerializerBase):
    def SetChunkAndDeflate(self, n_chunksize: typing.SupportsInt, n_deflateLevel: typing.SupportsInt) -> None:
        ...
    def SetCollectiveRW(self, arg0: bool, arg1: bool) -> None:
        ...
    def __init__(self, mpi: DNDSR.DNDS._ext.dnds_pybind11.MPIInfo) -> None:
        ...
class SerializerJSON(SerializerBase):
    def SetDeflateLevel(self, arg0: typing.SupportsInt) -> None:
        ...
    def SetUseCodecOnUint8(self, arg0: bool) -> None:
        ...
    def __init__(self) -> None:
        ...
