// Auto-generated by _generate_AdjPairTracked_bind.py — do not edit.
#include "../AdjPairTracked_bind.hpp"

void pybind11_AdjPairTracked_2_2_N_define(py::module_ &m)
{
    DNDS::Geom::pybind11_AdjPairTracked_define<2, 2, -1024>(m);
}
