import DNDSR.DNDS._ext.dnds_pybind11
from __future__ import annotations
import collections.abc
__all__: list[str] = ['Allreduce', 'Finalize', 'GetMPIThreadLevel', 'Init_thread']
def Allreduce(send: collections.abc.Buffer, recv: collections.abc.Buffer, op: str, mpi: DNDSR.DNDS._ext.dnds_pybind11.MPIInfo) -> None:
    ...
def Finalize() -> int:
    ...
def GetMPIThreadLevel() -> int:
    ...
def Init_thread(arg0: collections.abc.Sequence[str]) -> tuple[int, list[str]]:
    ...
