#!/bin/bash
# DEPRECATED: Stub generation is now automatic during install.
# Stubs are regenerated by:
#   cmake --install build --component py
#   pip install -e . --no-build-isolation
# See cmake/DndsTooling.cmake for implementation.
#
# This script is kept for reference only.  Do NOT install it as a
# pre-commit hook — it is no longer needed.
#
# --- Original description ---
# Pre-commit hook: regenerate .pyi stubs if pybind11 bindings changed.
#
# Install: cp scripts/pre-commit .git/hooks/pre-commit && chmod +x .git/hooks/pre-commit
# Or:      ln -sf ../../scripts/pre-commit .git/hooks/pre-commit
#
# This hook checks if any *_pybind*.cpp or *_bind*.cpp files are staged.
# If so, it attempts to regenerate stubs and stage the updated .pyi files.
# If stubgen fails (e.g. package not installed), it prints a warning but
# does NOT block the commit.

set -eo pipefail

# Check if any pybind binding sources are staged
BINDING_CHANGES=$(git diff --cached --name-only -- '*.cpp' | grep -E '_pybind|_bind' || true)

if [ -z "$BINDING_CHANGES" ]; then
    exit 0
fi

echo "[pre-commit] Pybind11 binding changes detected:"
echo "$BINDING_CHANGES"
echo "[pre-commit] Regenerating type stubs..."

# Locate project root
PROJECT_ROOT="$(git rev-parse --show-toplevel)"

# Try to find a Python with pybind11-stubgen
STUBGEN=""
for candidate in \
    "${PROJECT_ROOT}/venv/bin/pybind11-stubgen" \
    "$(which pybind11-stubgen 2>/dev/null)" \
; do
    if [ -x "$candidate" ]; then
        STUBGEN="$candidate"
        break
    fi
done

if [ -z "$STUBGEN" ]; then
    echo "[pre-commit] WARNING: pybind11-stubgen not found; skipping stub generation."
    echo "[pre-commit] Install it: pip install pybind11-stubgen"
    exit 0
fi

# Check if the package is importable
PYTHON="${STUBGEN%/*}/python"
if [ ! -x "$PYTHON" ]; then
    PYTHON="$(which python3 2>/dev/null || which python 2>/dev/null)"
fi

if ! PYTHONPATH="${PROJECT_ROOT}/python" "$PYTHON" -c "import DNDSR" 2>/dev/null; then
    echo "[pre-commit] WARNING: DNDSR package not importable; skipping stub generation."
    echo "[pre-commit] Run: pip install -e . --no-build-isolation"
    exit 0
fi

# Run stubgen
PYTHONPATH="${PROJECT_ROOT}/python" \
    PATH="$(dirname "$STUBGEN"):$PATH" \
    bash "${PROJECT_ROOT}/scripts/generate-stubs.sh" 2>&1 | tail -3

# Stage any changed .pyi files
git add "${PROJECT_ROOT}/python/DNDSR/"**/*.pyi "${PROJECT_ROOT}/stubs/" 2>/dev/null || true

echo "[pre-commit] Type stubs regenerated and staged."
