#!/usr/bin/env python3
"""Generate AdjWithState pybind11 instantiation .cpp files and forward header.

Each .cpp file instantiates pybind11_AdjWithState_define for one
(row_size, row_max, align) triple.  The forward header declares all
define functions so the module entry point can call them.

Follows the same pattern as DNDS/ArrayDOF_inst/_generate_explicit_inst.py.

Usage:
    python _generate_AdjWithState_bind.py
"""

import os
import textwrap

# (row_size, row_max, align)
# Python class names are generated at compile time by the
# pybind11_AdjWithState_name<rs, rm, al>() helper.
INSTANTIATIONS = [
    (-2, -2, -1024),  # tAdjPair  (NonUniformSize)
    (2, 2, -1024),    # tAdj2Pair
    (1, 1, -1024),    # tAdj1Pair
]

# Map special rowsize/align values to the same short tags used by
# RowSize_To_PySnippet / Align_To_PySnippet in Defines.hpp.
_RS_MAP = {-2: "I", -1: "D"}
_AL_MAP = {-1024: "N"}


def _tag(rs, rm, al):
    r = _RS_MAP.get(rs, str(rs))
    m = _RS_MAP.get(rm, str(rm))
    a = _AL_MAP.get(al, str(al))
    return f"{r}_{m}_{a}"


CPP_TEMPLATE = textwrap.dedent("""\
    // Auto-generated by _generate_AdjWithState_bind.py — do not edit.
    #include "../AdjWithState_bind.hpp"

    void pybind11_AdjWithState_{tag}_define(py::module_ &m)
    {{
        DNDS::Geom::pybind11_AdjWithState_define<{rs}, {rm}, {al}>(m);
    }}
""")

FWD_HEADER_HEAD = textwrap.dedent("""\
    // Auto-generated by _generate_AdjWithState_bind.py — do not edit.
    #pragma once
    #include <pybind11/pybind11.h>
    namespace py = pybind11;

""")

DIR = os.path.dirname(os.path.abspath(__file__))


def main():
    for rs, rm, al in INSTANTIATIONS:
        tag = _tag(rs, rm, al)
        cpp = CPP_TEMPLATE.format(tag=tag, rs=rs, rm=rm, al=al)
        path = os.path.join(DIR, f"AdjWithState_bind_{tag}.cpp")
        with open(path, "w") as f:
            f.write(cpp)
        print(f"  wrote {path}")

    header = FWD_HEADER_HEAD
    for rs, rm, al in INSTANTIATIONS:
        tag = _tag(rs, rm, al)
        header += f"void pybind11_AdjWithState_{tag}_define(py::module_ &m);\n"

    fwd_path = os.path.join(DIR, "AdjWithState_bind_fwd.hpp")
    with open(fwd_path, "w") as f:
        f.write(header)
    print(f"  wrote {fwd_path}")


if __name__ == "__main__":
    main()
