// Auto-generated by _generate_AdjWithState_bind.py — do not edit.
#pragma once
#include <pybind11/pybind11.h>
namespace py = pybind11;

void pybind11_AdjWithState_I_I_N_define(py::module_ &m);
void pybind11_AdjWithState_2_2_N_define(py::module_ &m);
void pybind11_AdjWithState_1_1_N_define(py::module_ &m);
