// Auto-generated by _generate_AdjWithState_bind.py — do not edit.
#include "../AdjWithState_bind.hpp"

void pybind11_AdjWithState_I_I_N_define(py::module_ &m)
{
    DNDS::Geom::pybind11_AdjWithState_define<-2, -2, -1024>(m);
}
